"""Pinned formal daily review function, trigger and command-seal catalog."""
from sqlalchemy import text

TABLES = frozenset({'daily_review_bindings', 'daily_review_events', 'daily_review_consumptions'})
FUNCTIONS = {('rsc_daily_review_hash_0132', 'jsonb'): {'definition': ('v',
                                                          True,
                                                          'plpgsql',
                                                          ('search_path=pg_catalog, public',)),
                                           'shape': ('f', 'text', False),
                                           'sha256': '2b7db1a03b5f8247e13077ec0ecf3f217674561110b943e3d966ff87cfacf869',
                                           'api': False},
 ('rsc_daily_review_snapshot_0132', 'uuid'): {'definition': ('v',
                                                             True,
                                                             'plpgsql',
                                                             ('search_path=pg_catalog, public',)),
                                              'shape': ('f', 'jsonb', False),
                                              'sha256': 'f8a1e50bce06977cd22d45f59c7d2be4dc9ec92c5b90c1816afe3090b88b6d76',
                                              'api': False},
 ('rsc_daily_review_live_0132', 'daily_review_events, timestamp with time zone'): {'definition': ('v',
                                                                                                  True,
                                                                                                  'plpgsql',
                                                                                                  ('search_path=pg_catalog, '
                                                                                                   'public',)),
                                                                                   'shape': ('f',
                                                                                             'void',
                                                                                             False),
                                                                                   'sha256': '7e1e1a97041882becf636813ac18260d94fd2a02eb6cbc382bc73e271b04a469',
                                                                                   'api': False},
 ('rsc_daily_review_step_0132', 'jsonb, jsonb, jsonb'): {'definition': ('v',
                                                                        True,
                                                                        'plpgsql',
                                                                        ('search_path=pg_catalog, public',)),
                                                         'shape': ('f', 'jsonb', False),
                                                         'sha256': '135998910824733864eaf9a871d3f74130e26554572e808e9ff0ac4526597985',
                                                         'api': False},
 ('rsc_guard_daily_review_event_0132', ''): {'definition': ('v',
                                                            True,
                                                            'plpgsql',
                                                            ('search_path=pg_catalog, public',)),
                                             'shape': ('f', 'trigger', False),
                                             'sha256': 'af4ae67fc3925ebe5835eb484c7f2926bdfa7218e4cfef22eb9384d27aa4acd7',
                                             'api': False},
 ('rsc_guard_daily_review_binding_0132', ''): {'definition': ('v',
                                                              True,
                                                              'plpgsql',
                                                              ('search_path=pg_catalog, public',)),
                                               'shape': ('f', 'trigger', False),
                                               'sha256': '43236d0e47f45913f0171e2f0435830451823be2877e2301e6a686d527165d6e',
                                               'api': False},
 ('rsc_daily_review_projection_gate_0132', 'uuid'): {'definition': ('v',
                                                                    True,
                                                                    'plpgsql',
                                                                    ('search_path=pg_catalog, public',)),
                                                     'shape': ('f', 'void', False),
                                                     'sha256': '0f07b2f0c21515ee47594fcc03a38b26ef9cc366608d4c58758741b344e1930f',
                                                     'api': True},
 ('rsc_daily_review_projection_proof_0132', 'uuid'): {'definition': ('v',
                                                                     True,
                                                                     'plpgsql',
                                                                     ('search_path=pg_catalog, public',)),
                                                      'shape': ('f', 'void', False),
                                                      'sha256': '686cc9484504513a6aeaa5f2ba6166c770d4695cfac77273440835396d12fc60',
                                                      'api': False},
 ('rsc_guard_daily_review_consumption_0132', ''): {'definition': ('v',
                                                                  True,
                                                                  'plpgsql',
                                                                  ('search_path=pg_catalog, public',)),
                                                   'shape': ('f', 'trigger', False),
                                                   'sha256': 'eed393e30c030e33fc7099d650bccecf3bed6cf9ec960571264a621864cd0faf',
                                                   'api': False},
 ('rsc_guard_daily_review_commit_0132', ''): {'definition': ('v',
                                                             True,
                                                             'plpgsql',
                                                             ('search_path=pg_catalog, public',)),
                                              'shape': ('f', 'trigger', False),
                                              'sha256': '65615e78b7bf316dbc1268b78b75620580c4079a085ad45f2aeac9e7ce1abee3',
                                              'api': False},
 ('rsc_guard_daily_review_transition_0132', ''): {'definition': ('v',
                                                                 True,
                                                                 'plpgsql',
                                                                 ('search_path=pg_catalog, public',)),
                                                  'shape': ('f', 'trigger', False),
                                                  'sha256': '2a9862c9d9b25a0e2fb329f5d6a7e18cf95db3284fbf9efcc4a390393a838b32',
                                                  'api': False},
 ('rsc_guard_daily_review_audit_0132', ''): {'definition': ('v',
                                                            True,
                                                            'plpgsql',
                                                            ('search_path=pg_catalog, public',)),
                                             'shape': ('f', 'trigger', False),
                                             'sha256': 'a231a1468ae632d4d8a3fb8e324e03aca0a2f6cccd359c992b83865d0a44f046',
                                             'api': False}}
TRIGGERS = {'trg_daily_review_events_facts_0132': ('daily_review_events',
                                        'rsc_guard_daily_review_event_0132',
                                        'A',
                                        31,
                                        False,
                                        False,
                                        False),
 'trg_daily_review_events_truncate_0132': ('daily_review_events',
                                           'rsc_guard_daily_review_event_0132',
                                           'A',
                                           34,
                                           False,
                                           False,
                                           False),
 'trg_daily_review_bindings_facts_0132': ('daily_review_bindings',
                                          'rsc_guard_daily_review_binding_0132',
                                          'A',
                                          31,
                                          False,
                                          False,
                                          False),
 'trg_daily_review_bindings_truncate_0132': ('daily_review_bindings',
                                             'rsc_guard_daily_review_binding_0132',
                                             'A',
                                             34,
                                             False,
                                             False,
                                             False),
 'trg_daily_review_consumptions_facts_0132': ('daily_review_consumptions',
                                              'rsc_guard_daily_review_consumption_0132',
                                              'A',
                                              31,
                                              False,
                                              False,
                                              False),
 'trg_daily_review_consumptions_truncate_0132': ('daily_review_consumptions',
                                                 'rsc_guard_daily_review_consumption_0132',
                                                 'A',
                                                 34,
                                                 False,
                                                 False,
                                                 False),
 'trg_daily_review_commit_0132': ('daily_review_events',
                                  'rsc_guard_daily_review_commit_0132',
                                  'A',
                                  5,
                                  True,
                                  True,
                                  True),
 'trg_daily_review_transition_facts_0132': ('state_transition_events',
                                            'rsc_guard_daily_review_transition_0132',
                                            'A',
                                            31,
                                            False,
                                            False,
                                            False),
 'trg_daily_review_transition_truncate_0132': ('state_transition_events',
                                               'rsc_guard_daily_review_transition_0132',
                                               'A',
                                               34,
                                               False,
                                               False,
                                               False),
 'trg_daily_review_transition_commit_0132': ('state_transition_events',
                                             'rsc_guard_daily_review_transition_0132',
                                             'A',
                                             5,
                                             True,
                                             True,
                                             True),
 'trg_daily_review_audit_facts_0132': ('audit_events',
                                       'rsc_guard_daily_review_audit_0132',
                                       'A',
                                       7,
                                       False,
                                       False,
                                       False),
 'trg_daily_review_audit_commit_0132': ('audit_events',
                                        'rsc_guard_daily_review_audit_0132',
                                        'A',
                                        5,
                                        True,
                                        True,
                                        True)}
PROJECTION_GUARD_HASHES = {('rsc_guard_reconciliation_run_projection_0026', ''): 'a5930fcc0b93f3366213f2eb966180098edd58d93c04f45ca251015eb945f6f0', ('rsc_guard_reconciliation_item_projection_0026', ''): '9d12e367c6a96be506b441a7b6b0a9668a7f43daa79e4340cdd9263ccd2fe265'}

# A missing cyclic FK would permit an unconsumed command to commit. Verify
# both constraints and their internal enforcement triggers at startup.
SEAL_SQL = text("""
SELECT c.conname, c.conrelid::regclass::text AS source_table,
 c.confrelid::regclass::text AS target_table,
 pg_get_constraintdef(c.oid,true) AS definition,
 c.convalidated AND c.condeferrable AND c.condeferred AS flags_safe,
 (SELECT count(*)=4 AND bool_and(t.tgisinternal AND t.tgenabled='O')
  FROM pg_trigger t WHERE t.tgconstraint=c.oid) AS triggers_safe
FROM pg_constraint c WHERE c.connamespace='public'::regnamespace
 AND c.conname IN ('fk_daily_review_event_consumed','fk_daily_review_event_run')
ORDER BY c.conname
""")
SEALS = [
 ('fk_daily_review_event_consumed','daily_review_events','daily_review_consumptions',
  'FOREIGN KEY (id) REFERENCES daily_review_consumptions(event_id) DEFERRABLE INITIALLY DEFERRED'),
 ('fk_daily_review_event_run','daily_review_events','daily_review_bindings',
  'FOREIGN KEY (run_id) REFERENCES daily_review_bindings(run_id) DEFERRABLE INITIALLY DEFERRED'),
]

class DailyReviewSecurityError(RuntimeError):
    pass

def validate_review_catalog(connection):
    rows=connection.execute(SEAL_SQL).mappings().all()
    if len(rows)!=2 or any(
        tuple(r[k] for k in ('conname','source_table','target_table','definition'))!=expected
        or r['flags_safe'] is not True or r['triggers_safe'] is not True
        for r,expected in zip(rows,SEALS)
    ):
        raise DailyReviewSecurityError('daily_review_command_seal_catalog_drift')
