"""Pinned 0130 SQL definitions; no runtime migration imports."""

FUNCTIONS = {('rsc_validate_daily_mapping_0130', 'jsonb, uuid, uuid'): {'shape': ('f', 'void', False),
                                                            'definition': ('v',
                                                                           False,
                                                                           'plpgsql',
                                                                           ('search_path=pg_catalog, '
                                                                            'public',)),
                                                            'sha256': 'dd3cae1c40f0cb87f9a4aefc0a319156ebb60cf0d14fff2e92b22ece6323204f'},
 ('rsc_guard_daily_mapping_0130', ''): {'shape': ('f', 'trigger', False),
                                        'definition': ('v',
                                                       False,
                                                       'plpgsql',
                                                       ('search_path=pg_catalog, public',)),
                                        'sha256': 'f7648152a740c1700ac6f359c067cdb74f9ffe61dd891e3c66696217c2cf07b4'},
 ('rsc_guard_daily_cutoff_0130', ''): {'shape': ('f', 'trigger', False),
                                       'definition': ('v',
                                                      False,
                                                      'plpgsql',
                                                      ('search_path=pg_catalog, public',)),
                                       'sha256': 'baa260ca3ef056afa6427d57af0235047d11ba7f8a0eecce4910bec558e42182'},
 ('rsc_guard_daily_commit_0130', ''): {'shape': ('f', 'trigger', False),
                                       'definition': ('v',
                                                      False,
                                                      'plpgsql',
                                                      ('search_path=pg_catalog, public',)),
                                       'sha256': 'e7143e16364a0c2d8e3bd9b6be3a3a0d6af12527ca384d793a73614718aeaf3f'}}

TRIGGERS = {'trg_daily_mapping_facts_0130': ('daily_comparison_mapping_decisions',
                                  'rsc_guard_daily_mapping_0130',
                                  'A',
                                  31,
                                  False,
                                  False,
                                  False),
 'trg_daily_mapping_truncate_0130': ('daily_comparison_mapping_decisions',
                                     'rsc_guard_daily_mapping_0130',
                                     'A',
                                     34,
                                     False,
                                     False,
                                     False),
 'trg_daily_mapping_commit_0130': ('daily_comparison_mapping_decisions',
                                   'rsc_guard_daily_commit_0130',
                                   'A',
                                   5,
                                   True,
                                   True,
                                   True),
 'trg_daily_cutoff_facts_0130': ('daily_reconciliation_cutoffs',
                                 'rsc_guard_daily_cutoff_0130',
                                 'A',
                                 31,
                                 False,
                                 False,
                                 False),
 'trg_daily_cutoff_truncate_0130': ('daily_reconciliation_cutoffs',
                                    'rsc_guard_daily_cutoff_0130',
                                    'A',
                                    34,
                                    False,
                                    False,
                                    False),
 'trg_daily_cutoff_commit_0130': ('daily_reconciliation_cutoffs',
                                  'rsc_guard_daily_commit_0130',
                                  'A',
                                  5,
                                  True,
                                  True,
                                  True)}

TABLES = frozenset({'daily_reconciliation_cutoffs', 'daily_comparison_mapping_decisions'})
