import { useEffect, useState } from "react";
import { mutationHeaders } from "./api";
import type { FormalMaterialRequestAdapter } from "./formalMaterialRequestAdapter";
import type { MaterialRequestDetail } from "./formalMaterialRequests";
import { type InboundOrderResult, type ReceiptResult, type ShipmentResult, validateInboundOrderResult, validateInboundPostingResult } from "./materialRequestShipment";
import { Button, Field, showError } from "./ui";

type Props={adapter:FormalMaterialRequestAdapter;detail:MaterialRequestDetail|null};
export default function FormalMaterialRequestInboundPanel({adapter,detail}:Props){
 const [receipt,setReceipt]=useState(""),[location,setLocation]=useState(""),[person,setPerson]=useState(""),[order,setOrder]=useState<InboundOrderResult|null>(null),[history,setHistory]=useState<InboundOrderResult[]>([]),[receipts,setReceipts]=useState<ReceiptResult[]>([]),[shipments,setShipments]=useState<ShipmentResult[]>([]),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;if(!detail)return;const loads=[adapter.listInboundOrders?adapter.listInboundOrders(detail.request_id):Promise.resolve([]),adapter.listReceipts?adapter.listReceipts(detail.request_id):Promise.resolve([]),adapter.listShipments?adapter.listShipments(detail.request_id):Promise.resolve([])];Promise.all(loads).then(([orders,accepted,shipped])=>{if(!live)return;setHistory([...(orders as InboundOrderResult[])]);setReceipts([...(accepted as ReceiptResult[])]);setShipments([...(shipped as ShipmentResult[])])}).catch(e=>{if(live)setError(showError(e))});return()=>{live=false}},[adapter,detail?.request_id]);
 if(!detail)return null; const requestId=detail.request_id; const requestVersion=detail.request_version;
 function selectOrder(value: InboundOrderResult){setOrder(value);setReceipt(value.receipt_id);setLocation(value.target_location_id);setPerson(value.target_person_id);setBlocked(false);setError("");}
 function selectReceipt(value:string){setReceipt(value);const shipmentId=receipts.find(item=>item.receipt_id===value)?.shipment_id;const shipment=shipments.find(item=>item.shipment_id===shipmentId);if(shipment){setLocation(shipment.target_location_id);setPerson(shipment.target_person_id??"");}else{setLocation("");setPerson("");}}
 async function create(){if(!adapter.createInboundOrder)return;setBusy(true);setError("");try{const h=mutationHeaders("material-request-inbound");const x=await adapter.createInboundOrder(requestId,{expected_request_version:requestVersion,receipt_id:receipt,target_location_id:location,target_person_id:person},{"X-Request-ID":new Headers(h.headers).get("X-Request-ID")!});const result=validateInboundOrderResult(x);selectOrder(result);setHistory(prev=>[result,...prev.filter(row=>row.inbound_order_id!==result.inbound_order_id)]);setMessage(`已创建待入账单 ${x.inbound_no}`)}catch(e){setError(showError(e))}finally{setBusy(false)}}
 async function verify(){if(!order||!adapter.listInboundOrders)return;setBusy(true);setError("");try{const rows=(await adapter.listInboundOrders(requestId)).map(validateInboundOrderResult);setHistory(rows);const found=rows.find(row=>row.inbound_order_id===order.inbound_order_id);if(!found)throw new Error("未找到原入账单，请保持页面等待后再核验");selectOrder(found);if(found.status==="posted"){setMessage("原个人仓入账已完成，已通过只读回读确认");}else{setMessage("原个人仓入账仍待处理；核验期间不会重新提交");}}catch(e){setError(showError(e))}finally{setBusy(false)}}
 async function post(){if(!order||!adapter.postInboundOrder||blocked)return;setBusy(true);setError("");try{const h=new Headers(mutationHeaders("material-request-inbound-post").headers);const x=validateInboundPostingResult(await adapter.postInboundOrder(requestId,order.inbound_order_id,{"X-Request-ID":h.get("X-Request-ID")!,"Idempotency-Key":h.get("Idempotency-Key")!}));const posted={...order,status:"posted",posting_transaction_id:x.inventory_transaction_id};setOrder(posted);setHistory(prev=>prev.map(row=>row.inbound_order_id===posted.inbound_order_id?posted:row));setMessage(`已完成个人仓入账，库存事务 ${x.inventory_transaction_id}`)}catch(e){setBlocked(true);setError("个人仓入账结果未知，已暂停重提交；请只读核验原入账单。"+showError(e))}finally{setBusy(false)}}
 return <section className="opening-detail-section" aria-label="个人仓入账"><header><div><h3>个人仓入账</h3><p>收货验收与库存入账分开确认；目标位置和人员来自发运事实，不能手工改写。</p></div></header>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-info" role="status">{message}</div>}{blocked&&<div className="alert alert-warning">入账结果待核验，已禁止再次提交。<Button disabled={busy} onClick={()=>void verify()}>只读核验原入账</Button></div>}<div className="form-grid"><Field label="收货单"><select aria-label="收货单" value={receipt} onChange={e=>selectReceipt(e.target.value)}><option value="">请选择已验收收货单</option>{receipts.map(item=><option key={item.receipt_id} value={item.receipt_id}>{item.receipt_no} / {item.status}</option>)}</select></Field><Field label="目标位置 ID"><input aria-label="目标位置 ID" value={location} readOnly /></Field><Field label="目标人员 ID"><input aria-label="目标人员 ID" value={person} readOnly /></Field></div><div><Button disabled={busy||!receipt||!location||!person} onClick={()=>void create()}>创建待入账单</Button>{order&&order.status!=="posted"&&<Button disabled={busy||blocked} onClick={()=>void post()}>确认个人仓入账</Button>}</div>{history.length>0&&<div className="table-wrap"><h4>个人仓入账历史</h4><table><thead><tr><th>入账单</th><th>收货单</th><th>状态</th><th>库存事务</th><th>操作</th></tr></thead><tbody>{history.map(x=><tr key={x.inbound_order_id}><td>{x.inbound_no}</td><td>{x.receipt_id}</td><td>{x.status}</td><td className="mono">{x.posting_transaction_id ?? "—"}</td><td>{x.status==="pending"&&<Button onClick={()=>selectOrder(x)}>继续处理</Button>}</td></tr>)}</tbody></table></div>}</section>;
}
