import { useEffect, useState } from "react";
import { mutationHeaders } from "./api";
import type { FormalMaterialRequestAdapter } from "./formalMaterialRequestAdapter";
import type { MaterialRequestDetail } from "./formalMaterialRequests";
import { type ReceiptInput, type ReceiptResult, type ShipmentResult, validateReceiptResult } from "./materialRequestShipment";
import { createReceiptStore, hasReceiptRecovery, recoverReceipt, type ReceiptStore, type ReceiptSentinel } from "./materialRequestReceiptRecovery";
import { validateFormalMaterialRequestFreshIdentity } from "./formalMaterialRequestAdapter";
import { Button, Field, showError } from "./ui";

type Props={adapter:FormalMaterialRequestAdapter;detail:MaterialRequestDetail|null;store?:ReceiptStore};
export default function FormalMaterialRequestReceiptPanel({adapter,detail,store:providedStore}:Props){
 const [store] = useState<ReceiptStore>(()=>providedStore ?? createReceiptStore());
 const [receiver,setReceiver]=useState(""),[line,setLine]=useState(""),[accepted,setAccepted]=useState(""),[rejected,setRejected]=useState("0.000"),[condition,setCondition]=useState("normal"),[serials,setSerials]=useState(""),[evidence,setEvidence]=useState(""),[history,setHistory]=useState<ReceiptResult[]>([]),[shipments,setShipments]=useState<ShipmentResult[]>([]),[busy,setBusy]=useState(false),[blocked,setBlocked]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const request=detail;
 useEffect(()=>{let live=true;if(!request)return;const loads=[adapter.listReceipts?adapter.listReceipts(request.request_id):Promise.resolve([]),adapter.listShipments?adapter.listShipments(request.request_id):Promise.resolve([])];Promise.all(loads).then(([receipts,shipped])=>{if(!live)return;setHistory([...(receipts as ReceiptResult[])]);setShipments([...(shipped as ShipmentResult[])])}).catch(e=>{if(live)setError(showError(e))});return()=>{live=false}},[adapter,request?.request_id]);
 useEffect(()=>{let live=true;const pending=store.read();if(!request||pending.kind!=="valid"||pending.value.request_id.toLowerCase()!==request.request_id.toLowerCase())return()=>{live=false};if(!hasReceiptRecovery(adapter))return()=>{live=false};setBlocked(true);recoverReceipt(adapter,store,pending.value).then(({command})=>{if(live){setBlocked(false);setHistory(prev=>[command,...prev.filter(x=>x.receipt_id!==command.receipt_id)]);setMessage(`已通过只读回读确认原收货 ${command.receipt_no}`)}}).catch(e=>{if(live)setError("收货结果待核验，已禁止再次提交。"+showError(e))});return()=>{live=false}},[adapter,request?.request_id,store]);
 if(!request||!adapter.createReceipt)return null;
 async function submit(){setBusy(true);setError("");try{const input:ReceiptInput={expected_request_version:request!.request_version,receiver_person_id:receiver,received_at:new Date().toISOString(),lines:[{shipment_line_id:line,accepted_qty:accepted,rejected_qty:rejected,condition,serial_ids:serials.split(",").map(x=>x.trim()).filter(Boolean),exception_evidence_file_id:evidence||null}]};const h=new Headers(mutationHeaders("material-request-receipt").headers);const trace=h.get("X-Request-ID")!,key=h.get("Idempotency-Key")!;if(adapter.loadIdentity){const identity=validateFormalMaterialRequestFreshIdentity(await adapter.loadIdentity());store.persist({v:1,kind:"receipt",trace,key,person_id:identity.person_id,authorization_version:identity.authorization_version,request_id:request!.request_id,input});}const result=validateReceiptResult(await adapter.createReceipt!(request!.request_id,input,{"X-Request-ID":trace,"Idempotency-Key":key}));const current=store.read();if(current.kind==="valid"&&current.value.trace===trace)store.clear(trace);setBlocked(false);setHistory(prev=>[result,...prev.filter(x=>x.receipt_id!==result.receipt_id)]);setMessage(`已登记收货 ${result.receipt_no}，状态 ${result.status}`)}catch(e){setBlocked(true);setError(showError(e))}finally{setBusy(false)}}
 return <section className="opening-detail-section" aria-label="收货验收"><header><div><h3>收货验收</h3><p>收货是独立事实；确认后仍需单独创建个人仓入账单并过账。</p></div></header>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-info" role="status">{message}</div>}{blocked&&<div className="alert alert-warning">收货结果待核验，已禁止再次提交。刷新后将只读核验原收货。</div>}<div className="form-grid"><Field label="收货人 ID"><input aria-label="收货人 ID" value={receiver} onChange={e=>setReceiver(e.target.value)} /></Field><Field label="发运明细"><select aria-label="发运明细" value={line} onChange={e=>setLine(e.target.value)}><option value="">请选择已登记发运明细</option>{shipments.flatMap(shipment=>shipment.lines.map(item=><option key={item.shipment_line_id} value={item.shipment_line_id}>{shipment.shipment_no} / {item.shipment_line_id} / {item.shipped_qty}</option>))}</select></Field><Field label="合格数量"><input aria-label="合格数量" value={accepted} onChange={e=>setAccepted(e.target.value)} /></Field><Field label="拒收数量"><input aria-label="拒收数量" value={rejected} onChange={e=>setRejected(e.target.value)} /></Field><Field label="验收条件"><select aria-label="验收条件" value={condition} onChange={e=>setCondition(e.target.value)}><option value="normal">normal</option><option value="shortage">shortage</option><option value="damaged">damaged</option><option value="wrong_material">wrong_material</option><option value="wrong_serial">wrong_serial</option><option value="rejected">rejected</option></select></Field><Field label="SN（逗号分隔，可选）"><input aria-label="SN（逗号分隔，可选）" value={serials} onChange={e=>setSerials(e.target.value)} /></Field><Field label="异常证据文件 ID（可选）"><input aria-label="异常证据文件 ID（可选）" value={evidence} onChange={e=>setEvidence(e.target.value)} /></Field></div><Button disabled={busy||blocked||!receiver||!line||!accepted||!adapter.createReceipt} onClick={()=>void submit()}>登记收货验收</Button>{history.length>0&&<div className="table-wrap"><h4>收货历史</h4><table><thead><tr><th>收货单</th><th>发运单</th><th>状态</th><th>异常数</th></tr></thead><tbody>{history.map(x=><tr key={x.receipt_id}><td>{x.receipt_no}</td><td>{x.shipment_id}</td><td>{x.status}</td><td>{x.exceptions.length}</td></tr>)}</tbody></table></div>}</section>;
}
