import { useEffect, useState } from "react";
import { mutationHeaders } from "./api";
import type { FormalMaterialRequestAccess, FormalMaterialRequestAdapter } from "./formalMaterialRequestAdapter";
import type { MaterialRequestDetail } from "./formalMaterialRequests";
import { type ShipmentOption, type ShipmentInput, type ShipmentResult, type LogisticsEventResult, validateShipmentResult } from "./materialRequestShipment";
import { Button, Field, showError } from "./ui";

type Props={adapter:FormalMaterialRequestAdapter;access:FormalMaterialRequestAccess|null;detail:MaterialRequestDetail|null};
export default function FormalMaterialRequestShipmentPanel({adapter,access,detail}:Props){
 const [options,setOptions]=useState<ShipmentOption[]>([]),[shipments,setShipments]=useState<ShipmentResult[]>([]),[events,setEvents]=useState<Record<string, LogisticsEventResult[]>>({}),[eventType,setEventType]=useState<"pickup"|"transit"|"signed"|"exception">("signed"),[eventSource,setEventSource]=useState("carrier"),[eventBusy,setEventBusy]=useState(false),[carrier,setCarrier]=useState(""),[tracking,setTracking]=useState(""),[target,setTarget]=useState(""),[person,setPerson]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;setOptions([]);setShipments([]);setEvents({});setError("");if(!detail||!access?.can_read_allocation_options||!adapter.listShipmentOptions)return;Promise.all([adapter.listShipmentOptions(detail.request_id),adapter.listShipments?.(detail.request_id) ?? Promise.resolve([])]).then(([p,s])=>{if(!live)return;setOptions([...p.items]);setShipments([...s]);if(adapter.listLogisticsEvents){Promise.all(s.map(x=>adapter.listLogisticsEvents!(detail.request_id,x.shipment_id).then(es=>[x.shipment_id,[...es]] as const))).then(rows=>{if(live)setEvents(Object.fromEntries(rows.map(([id, es])=>[id, [...es]])))}).catch(e=>{if(live)setError(showError(e))})}}).catch(e=>{if(live)setError(showError(e))});return()=>{live=false}},[adapter,access,detail?.request_id,detail?.request_version]);
 async function registerEvent(shipmentId:string){if(!detail||!adapter.createLogisticsEvent||eventBusy)return;setError("");setEventBusy(true);try{const h=new Headers(mutationHeaders("material-request-logistics-event").headers);const x=await adapter.createLogisticsEvent(detail.request_id,shipmentId,{event_type:eventType,event_at:new Date().toISOString(),source:eventSource,evidence_file_id:null,external_ref:null},{"X-Request-ID":h.get("X-Request-ID")!,"Idempotency-Key":h.get("Idempotency-Key")!});setEvents(prev=>({...prev,[shipmentId]:[...(prev[shipmentId]||[]),x]}));setMessage(`已登记物流事件：${eventType}`)}catch(e){setError(showError(e))}finally{setEventBusy(false)}}
 async function submit(option:ShipmentOption){if(!detail||!adapter.createShipment||busy)return;setError("");try{const input:ShipmentInput={expected_request_version:detail.request_version,target_location_id:target,target_person_id:person||null,carrier,tracking_no:tracking,shipped_at:new Date().toISOString(),lines:[{outbound_posting_id:option.posting_id,shipped_qty:option.shippable_qty,serial_ids:[...option.serial_ids]}]};setBusy(true);const h=new Headers(mutationHeaders("material-request-shipment").headers);const result=validateShipmentResult(await adapter.createShipment(detail.request_id,input,{"X-Request-ID":h.get("X-Request-ID")!,"Idempotency-Key":h.get("Idempotency-Key")!}));setMessage(`已登记 ${result.shipment_no}，运单 ${result.tracking_no}`);setOptions(options.filter(x=>x.posting_id!==option.posting_id));}catch(e){setError(showError(e))}finally{setBusy(false)}}
 if(!detail)return null;return <section className="opening-detail-section" aria-label="发运与分包"><header><div><h3>发运与分包</h3><p>发运只登记承运交接事实，不再次移动或扣减库存；可继续拆分同一出库事实。</p></div></header>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-info" role="status">{message}</div>}<div className="form-grid"><Field label="目标位置 ID"><input aria-label="目标位置 ID" value={target} onChange={e=>setTarget(e.target.value)} /></Field><Field label="目标人员 ID（可选）"><input aria-label="目标人员 ID（可选）" value={person} onChange={e=>setPerson(e.target.value)} /></Field><Field label="承运商"><input aria-label="承运商" value={carrier} onChange={e=>setCarrier(e.target.value)} /></Field><Field label="运单号"><input aria-label="运单号" value={tracking} onChange={e=>setTracking(e.target.value)} /></Field></div>{options.length===0?<p>当前没有可登记发运的已出库事实。</p>:<div className="table-wrap"><table><thead><tr><th>出库分包</th><th>可发运数量</th><th>SN</th><th>操作</th></tr></thead><tbody>{options.map(o=><tr key={o.posting_id}><td>{o.posting_no}<br />拣货 {o.pick_id}</td><td>{o.shippable_qty}</td><td>{o.serials.length?o.serials.map(s=>s.serial_no).join(", "):"无"}</td><td><Button disabled={busy||!target||!carrier||!tracking} onClick={()=>void submit(o)}>登记发运</Button></td></tr>)}</tbody></table></div>}{shipments.length>0&&<div className="table-wrap"><h4>物流事件历史</h4><div className="form-grid"><Field label="事件类型"><select aria-label="事件类型" value={eventType} onChange={e=>setEventType(e.target.value as typeof eventType)}><option value="pickup">pickup</option><option value="transit">transit</option><option value="signed">signed</option><option value="exception">exception</option></select></Field><Field label="事件来源"><input aria-label="事件来源" value={eventSource} onChange={e=>setEventSource(e.target.value)} /></Field></div><table><thead><tr><th>发运单</th><th>承运商/运单</th><th>事件</th><th>时间</th><th>来源</th></tr></thead><tbody>{shipments.flatMap(s=>(events[s.shipment_id]??[]).map(e=><tr key={e.event_id}><td>{s.shipment_no}</td><td>{s.carrier} / {s.tracking_no}</td><td>{e.event_type}</td><td>{e.event_at}</td><td>{e.source}</td></tr>))}</tbody></table>{shipments.map(s=>adapter.createLogisticsEvent&&<Button key={s.shipment_id} disabled={eventBusy||!eventSource} onClick={()=>void registerEvent(s.shipment_id)}>登记 {s.shipment_no} 事件</Button>)}</div>}</section>;
}
