import { useEffect, useState } from "react";
import { mutationHeaders } from "./api";
import type { FormalMaterialRequestAccess, FormalMaterialRequestAdapter } from "./formalMaterialRequestAdapter";
import type { MaterialRequestDetail } from "./formalMaterialRequests";
import { type OutboundOption, validateOutboundPage } from "./materialRequestOutbound";
import { type ShipmentInput, validateShipmentResult } from "./materialRequestShipment";
import { Button, Field, showError } from "./ui";

type Props={adapter:FormalMaterialRequestAdapter;access:FormalMaterialRequestAccess|null;detail:MaterialRequestDetail|null};
export default function FormalMaterialRequestShipmentPanel({adapter,access,detail}:Props){
 const [options,setOptions]=useState<OutboundOption[]>([]),[carrier,setCarrier]=useState(""),[tracking,setTracking]=useState(""),[target,setTarget]=useState(""),[person,setPerson]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 useEffect(()=>{let live=true;setOptions([]);setError("");if(!detail||!access?.can_read_allocation_options||!adapter.listOutboundOptions)return;Promise.all(detail.lines.filter(l=>["approved","partially_approved"].includes(l.status)).map(l=>adapter.listOutboundOptions!(detail.request_id,l.request_line_id).then(validateOutboundPage))).then(pages=>{if(live)setOptions(pages.flatMap(p=>p.items))}).catch(e=>{if(live)setError(showError(e))});return()=>{live=false}},[adapter,access,detail?.request_id,detail?.request_version]);
 async function submit(option:OutboundOption){if(!detail||!adapter.createShipment||busy)return;setError("");try{const input:ShipmentInput={expected_request_version:detail.request_version,target_location_id:target,target_person_id:person||null,carrier,tracking_no:tracking,shipped_at:new Date().toISOString(),lines:[{outbound_posting_id:option.pick_id,shipped_qty:option.outboundable_qty,serial_ids:option.serials.map(s=>s.serial_id)}]};setBusy(true);const h=new Headers(mutationHeaders("material-request-shipment").headers);const result=validateShipmentResult(await adapter.createShipment(detail.request_id,input,{"X-Request-ID":h.get("X-Request-ID")!,"Idempotency-Key":h.get("Idempotency-Key")!}));setMessage(`已登记 ${result.shipment_no}，运单 ${result.tracking_no}`);setOptions(options.filter(x=>x.pick_id!==option.pick_id));}catch(e){setError(showError(e))}finally{setBusy(false)}}
 if(!detail)return null;return <section className="opening-detail-section" aria-label="发运与分包"><header><div><h3>发运与分包</h3><p>发运只登记承运交接事实，不再次移动或扣减库存；可继续拆分同一出库事实。</p></div></header>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-info" role="status">{message}</div>}<div className="form-grid"><Field label="目标位置 ID"><input aria-label="目标位置 ID" value={target} onChange={e=>setTarget(e.target.value)} /></Field><Field label="目标人员 ID（可选）"><input aria-label="目标人员 ID" value={person} onChange={e=>setPerson(e.target.value)} /></Field><Field label="承运商"><input aria-label="承运商" value={carrier} onChange={e=>setCarrier(e.target.value)} /></Field><Field label="运单号"><input aria-label="运单号" value={tracking} onChange={e=>setTracking(e.target.value)} /></Field></div>{options.length===0?<p>当前没有可登记发运的已出库事实。</p>:<div className="table-wrap"><table><thead><tr><th>来源拣货</th><th>可发运数量</th><th>SN</th><th>操作</th></tr></thead><tbody>{options.map(o=><tr key={o.pick_id}><td>{o.outbound_no} / {o.pick_no}<br/>{o.sku_code} · {o.location_name}</td><td>{o.outboundable_qty}</td><td>{o.serials.length?o.serials.map(s=>s.serial_no).join(", "):"无"}</td><td><Button disabled={busy||!target||!carrier||!tracking} onClick={()=>void submit(o)}>登记发运</Button></td></tr>)}</tbody></table></div>}</section>;
}
