import { useState } from "react";
import { mutationHeaders } from "./api";
import type { FormalMaterialRequestAdapter } from "./formalMaterialRequestAdapter";
import type { MaterialRequestDetail } from "./formalMaterialRequests";
import { type ReceiptInput, validateReceiptResult } from "./materialRequestShipment";
import { Button, Field, showError } from "./ui";

type Props={adapter:FormalMaterialRequestAdapter;detail:MaterialRequestDetail|null};
export default function FormalMaterialRequestReceiptPanel({adapter,detail}:Props){
 const [receiver,setReceiver]=useState(""),[line,setLine]=useState(""),[accepted,setAccepted]=useState(""),[rejected,setRejected]=useState("0.000"),[condition,setCondition]=useState("normal"),[serials,setSerials]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 if(!detail||!adapter.createReceipt)return null; const request=detail;
 async function submit(){setBusy(true);setError("");try{const input:ReceiptInput={expected_request_version:request.request_version,receiver_person_id:receiver,received_at:new Date().toISOString(),lines:[{shipment_line_id:line,accepted_qty:accepted,rejected_qty:rejected,condition,serial_ids:serials.split(",").map(x=>x.trim()).filter(Boolean)}]};const h=new Headers(mutationHeaders("material-request-receipt").headers);const result=validateReceiptResult(await adapter.createReceipt!(request.request_id,input,{"X-Request-ID":h.get("X-Request-ID")!,"Idempotency-Key":h.get("Idempotency-Key")!}));setMessage(`已登记收货 ${result.receipt_no}，状态 ${result.status}`)}catch(e){setError(showError(e))}finally{setBusy(false)}}
 return <section className="opening-detail-section" aria-label="收货验收"><header><div><h3>收货验收</h3><p>收货是独立事实；确认后仍需单独创建个人仓入账单并过账。</p></div></header>{error&&<div className="alert alert-error">{error}</div>}{message&&<div className="alert alert-info" role="status">{message}</div>}<div className="form-grid"><Field label="收货人 ID"><input aria-label="收货人 ID" value={receiver} onChange={e=>setReceiver(e.target.value)} /></Field><Field label="发运明细 ID"><input aria-label="发运明细 ID" value={line} onChange={e=>setLine(e.target.value)} /></Field><Field label="合格数量"><input aria-label="合格数量" value={accepted} onChange={e=>setAccepted(e.target.value)} /></Field><Field label="拒收数量"><input aria-label="拒收数量" value={rejected} onChange={e=>setRejected(e.target.value)} /></Field><Field label="验收条件"><select aria-label="验收条件" value={condition} onChange={e=>setCondition(e.target.value)}><option value="normal">normal</option><option value="shortage">shortage</option><option value="damaged">damaged</option><option value="wrong_material">wrong_material</option><option value="wrong_serial">wrong_serial</option><option value="rejected">rejected</option></select></Field><Field label="SN（逗号分隔，可选）"><input aria-label="SN（逗号分隔，可选）" value={serials} onChange={e=>setSerials(e.target.value)} /></Field></div><Button disabled={busy||!receiver||!line||!accepted} onClick={()=>void submit()}>登记收货验收</Button></section>;
}
