import { expect, it, vi } from 'vitest';
import { createAdapter } from './lossReviewAdapter';
import { hash, type Pending } from './formalLossReview';
const id=(n:number)=>`10000000-0000-4000-8000-${n.toString().padStart(12,'0')}`;
const auth={person_id:id(1),name:'测试负责人',employee_no:'1',organization_code:'R1',organization_name:'区域',account_status:'active',employment_status:'active',access_mode:'active',authorization_version:2,role_codes:['provincial_manager']};
function access(){return {person_id:id(1),account_status:'active',employment_status:'active',access_mode:'active',authorization_version:2,role_codes:['provincial_manager'],assignments:[{assignment_id:id(2),role_code:'provincial_manager',scope_type:'organization',scope_id:id(3),valid_from:'2026-01-01T00:00:00Z',valid_to:null}],permissions:[{resource:'stock_operation',action:'read',field_code:''},{resource:'stock_operation',action:'review_loss_regional',field_code:''}]};}
it('uses fresh identity plus role/scope permissions and detects scope changes without a version bump',async()=>{let ctx=access();const request=vi.fn(async(path:string)=>path==='/auth/me'?auth:ctx);const adapter=createAdapter(id(1),request);const before=await adapter.context('regional');expect(before.can_read&&before.can_write).toBe(true);ctx={...ctx,assignments:[{...ctx.assignments[0],scope_id:id(4)}]};const after=await adapter.context('regional');expect(after.authority_hash).not.toBe(before.authority_hash);});
it('rejects switched identities and does not infer missing permissions',async()=>{const request=vi.fn(async(path:string)=>path==='/auth/me'?auth:{...access(),person_id:id(4)});await expect(createAdapter(id(1),request).context('regional')).rejects.toThrow();const limited=createAdapter(id(1),async path=>path==='/auth/me'?auth:{...access(),permissions:[]});expect((await limited.context('regional')).can_write).toBe(false);});
it('posts the original body and headers exactly once through the supplied no-replay transport',async()=>{const original={operation_id:id(2),expected_submission_plan_hash:'a'.repeat(64),comment:'确认核实',request_id:'original-request',idempotency_key:'original-key'};const {request_id:_r,idempotency_key:_k,...intent}=original;const p:Pending={v:1,person_id:id(1),authorization_version:2,owner_org_id:id(3),command:{stage:'regional',operator_person_id:id(1),request_hash:await hash(intent),original}};const request=vi.fn(async()=>{throw new Error('timeout');});const adapter=createAdapter(id(1),request);await expect(adapter.submit(p)).rejects.toThrow('timeout');expect(request).toHaveBeenCalledTimes(1);const [path,init]=request.mock.calls[0] as unknown as [string,RequestInit];expect(path).toBe('/v1/stock-operations/loss-reports/regional-reviews');expect(JSON.parse(init.body as string)).toEqual(p.command);expect(init.headers).toMatchObject({'X-Request-ID':'original-request','Idempotency-Key':'original-key'});});
it.each(['http://unsafe.test/a','https://user:secret@example.test/a','https://example.test/a#fragment'])('rejects unsafe signed URL %s',async url=>{const file={file_id:id(9),original_filename:'照片',sha256:'b'.repeat(64),size_bytes:1,mime_type:'image/jpeg'};const request=vi.fn(async(path:string)=>path==='/auth/me'?auth:path==='/access/context'?access():{schema_version:'1.0',file_id:file.file_id,purpose:'stock_loss_evidence',status:'available',download:{method:'GET',url,expires_at:new Date(Date.now()+60000).toISOString()}});await expect(createAdapter(id(1),request).download('regional',file)).rejects.toThrow();});
it('accepts the complete public file response after checking current scope again', async () => {
  const file = { file_id: id(9), original_filename: '照片', sha256: 'b'.repeat(64), size_bytes: 1, mime_type: 'image/jpeg' };
  const download = { method: 'GET', url: 'https://synthetic.invalid/proof', expires_at: new Date(Date.now() + 60000).toISOString() };
  const response = { schema_version: '1.0', file_id: file.file_id, purpose: 'stock_loss_evidence', status: 'available', download };
  const request = vi.fn(async (path: string) => path === '/auth/me' ? auth : path === '/access/context' ? access() : response);
  const adapter = createAdapter(id(1), request);
  expect(await adapter.download('regional', file)).toEqual({ url: download.url, expires_at: download.expires_at });
  expect(request.mock.calls.filter(([path]) => path.includes('/download-intent'))).toHaveLength(1);
  response.download.method = 'PUT'; await expect(adapter.download('regional', file)).rejects.toThrow();
});
