import { describe, expect, it, vi } from 'vitest';
import { canonical, command, detail, hash, pending, prepare, queue, report, resolution, verifyCommand, type Report, type Stage, type Pending } from './formalLossReview';
import { createStore, submit, recover, seal, type Locks, type Transport } from './lossReviewRecovery';
const id=(n:number)=>`10000000-0000-4000-8000-${n.toString().padStart(12,'0')}`;
const actor={person_id:id(1),authorization_version:3};
export function document(stage:Stage='regional'):Report {
  return {availability:'available',operation_id:id(2),operation_no:'LOSS-001',owner_org_id:id(3),owner_org_name:'测试区域',requester_person_id:id(4),requester_name:'申请人',source_location_id:id(5),source_location_name:'个人仓',submitted_at:'2026-09-30T01:00:00+00:00',reason:'损坏待核实',submission_plan_hash:'a'.repeat(64),approval_stage:stage==='regional'?'awaiting_regional':'awaiting_headquarters',approval_stock_effect:'none',lines:[{line_id:id(6),material_id:id(7),sku_code:'M1',material_name:'备件',base_unit:'件',condition_code:'new',lot_id:null,lot_no:null,quantity:'1.000',serials:[{serial_id:id(8),serial_no:'SN-1'}]}],evidence:[{file_id:id(9),original_filename:'照片.jpg',sha256:'b'.repeat(64),size_bytes:128,mime_type:'image/jpeg'}],regional_review:stage==='regional'?null:{review_id:id(10),reviewer_person_id:id(11),request_hash:'c'.repeat(64),comment:'区域核实',reviewed_at:'2026-09-30T01:01:00+00:00'},headquarters_review:null};
}
class Memory { values=new Map<string,string>();get length(){return this.values.size;}key(i:number){return [...this.values.keys()][i]??null;}getItem(k:string){return this.values.get(k)??null;}setItem(k:string,v:string){this.values.set(k,v);}removeItem(k:string){this.values.delete(k);} }
const locks:Locks={async request(_n,_o,fn){return fn({});}};
function found(p:Pending){const c=p.command,o=c.original;return {lookup_status:'found',retry_permitted:false,review:{review_id:id(12),operation_id:o.operation_id,owner_org_id:p.owner_org_id,reviewer_person_id:p.person_id,approval_stage:c.stage==='regional'?'awaiting_headquarters':'approved',stock_effect:'none',decision:c.stage==='regional'?'verified':'approved',comment:o.comment,request_id:o.request_id,request_hash:c.request_hash,submission_plan_hash:o.expected_submission_plan_hash,reviewed_at:'2026-09-30T01:02:00+00:00',...(c.stage==='headquarters'?{regional_review_id:o.regional_review_id,regional_review_hash:o.expected_regional_review_hash,decisions:o.decisions,disposition_stage:'pending'}:{})}};}
function sealed(p:Pending){const c=p.command,o=c.original;return {lookup_status:'sealed',retry_permitted:false,seal:{seal_id:id(13),stage:c.stage,operation_id:o.operation_id,owner_org_id:p.owner_org_id,reviewer_person_id:p.person_id,request_id:o.request_id,request_hash:c.request_hash,submission_plan_hash:o.expected_submission_plan_hash,stock_effect:'none',sealed_at:'2026-09-30T01:02:00+00:00'}};}
async function world(stage:Stage='regional'){
 const d=document(stage),p=await prepare(actor,stage,d,'已核对照片',stage==='headquarters'?[{line_id:id(6),disposition:'return_to_region',reason:'退回检查'}]:undefined);
 const storage=new Memory(),store=createStore(storage,locks);let result:unknown={lookup_status:'not_found',retry_permitted:false};
 const transport:Transport={context:vi.fn(async()=>({...actor,stage,authority_hash:'d'.repeat(64),can_read:true,can_write:true})),detail:vi.fn(async()=>d),lookup:vi.fn(async()=>result),submit:vi.fn(async()=>{result=found(p);return found(p).review;}),seal:vi.fn(async()=>{result=sealed(p);return result;})};
 return {d,p,storage,store,transport,setResult(v:unknown){result=v;},save:()=>store.withLease(p.person_id,stage,p.command.original.operation_id,async lease=>lease.persist(p))};
}

describe.each(['regional','headquarters'] as Stage[])('%s recovery',stage=>{
 it('persists before one write, verifies exact readback and clears only that request',async()=>{const w=await world(stage);const send=w.transport.submit;w.transport.submit=vi.fn(async p=>{expect(w.store.list(actor.person_id)).toEqual([w.p]);return send(p);});expect(await submit(w.transport,w.store,w.p)).toEqual({status:'found'});expect(w.transport.submit).toHaveBeenCalledTimes(1);expect(w.transport.lookup).toHaveBeenCalledTimes(1);expect(w.store.list(actor.person_id)).toEqual([]);});
 it('keeps unknown writes, missing lookup never permits resubmission, and recovers after revoked write',async()=>{const w=await world(stage);w.transport.submit=vi.fn(async()=>{throw new Error('timeout');});await expect(submit(w.transport,w.store,w.p)).rejects.toThrow('timeout');expect(w.store.list(actor.person_id)).toEqual([w.p]);expect(await recover(w.transport,w.store,w.p)).toEqual({status:'pending'});await expect(submit(w.transport,w.store,w.p)).rejects.toThrow();expect(w.transport.submit).toHaveBeenCalledTimes(1);w.transport.context=vi.fn(async()=>({...actor,authorization_version:4,stage,authority_hash:'d'.repeat(64),can_read:true,can_write:false}));w.setResult(found(w.p));expect(await recover(w.transport,w.store,w.p)).toEqual({status:'found'});expect(w.transport.seal).not.toHaveBeenCalled();});
 it('seals only the saved original after a fresh miss and exact confirmation',async()=>{const w=await world(stage);await w.save();expect(await seal(w.transport,w.store,w.p)).toEqual({status:'sealed'});expect(w.transport.submit).not.toHaveBeenCalled();expect(w.transport.seal).toHaveBeenCalledExactlyOnceWith(w.p);expect(w.transport.lookup).toHaveBeenCalledTimes(2);expect(w.store.list(actor.person_id)).toEqual([]);});
 it('existing committed proof prevents a seal write',async()=>{const w=await world(stage);await w.save();w.setResult(found(w.p));expect(await seal(w.transport,w.store,w.p)).toEqual({status:'found'});expect(w.transport.seal).not.toHaveBeenCalled();});
 it('revoked read and identity switch keep the saved request and never query another actor',async()=>{const w=await world(stage);await w.save();w.transport.context=vi.fn(async()=>({...actor,person_id:id(99),stage,authority_hash:'d'.repeat(64),can_read:true,can_write:true}));await expect(recover(w.transport,w.store,w.p)).rejects.toThrow();expect(w.transport.lookup).not.toHaveBeenCalled();expect(w.store.list(actor.person_id)).toEqual([w.p]);});
 it('page departure after commit leaves proof to be recovered later',async()=>{const w=await world(stage);let active=true;const send=w.transport.submit;w.transport.submit=async p=>{const r=await send(p);active=false;return r;};await expect(submit(w.transport,w.store,w.p,()=>active)).rejects.toThrow();expect(w.store.list(actor.person_id)).toEqual([w.p]);});
 it('storage failure or unavailable lock prevents every POST',async()=>{const w=await world(stage);w.storage.setItem=()=>{throw new Error();};await expect(submit(w.transport,w.store,w.p)).rejects.toThrow();expect(w.transport.submit).not.toHaveBeenCalled();const unlocked=createStore(new Memory(),null);await expect(submit(w.transport,unlocked,w.p)).rejects.toThrow();expect(w.transport.submit).not.toHaveBeenCalled();});
 it('rejects changed plan or request hash before any write',async()=>{const w=await world(stage);w.transport.detail=async()=>({...w.d,submission_plan_hash:'f'.repeat(64)});await expect(submit(w.transport,w.store,w.p)).rejects.toThrow();expect(w.transport.submit).not.toHaveBeenCalled();await expect(verifyCommand({...w.p.command,request_hash:'f'.repeat(64)})).rejects.toThrow();});
 it('wrong object or stock-changing proof cannot clear recovery',async()=>{const w=await world(stage);await w.save();const wrong=found(w.p);wrong.review.operation_id=id(99);w.setResult(wrong);await expect(recover(w.transport,w.store,w.p)).rejects.toThrow();expect(w.store.list(actor.person_id)).toEqual([w.p]);expect(()=>resolution({...sealed(w.p),retry_permitted:true},w.p)).toThrow();});
});

it('blocks concurrent commands for the same exact object',async()=>{const w=await world();let release!:()=>void;const waiting=new Promise<void>(r=>release=r);const send=w.transport.submit;w.transport.submit=vi.fn(async p=>{await waiting;return send(p);});const first=submit(w.transport,w.store,w.p);await vi.waitFor(()=>expect(w.transport.submit).toHaveBeenCalledTimes(1));await expect(submit(w.transport,w.store,w.p)).rejects.toThrow();release();await first;});
it('corrupt saved content is retained and cannot be overwritten',async()=>{const w=await world();await w.save();w.storage.values.set(w.storage.key(0)!,JSON.stringify({...w.p,owner_org_id:'bad'}));expect(()=>w.store.list(actor.person_id)).toThrow();await expect(submit(w.transport,w.store,w.p)).rejects.toThrow();expect(w.transport.submit).not.toHaveBeenCalled();expect(w.storage.length).toBe(1);});
it('checks query identity, self approval and complete serial quantities',()=>{const d=document(),base={schema_version:'1.0',...actor,stage:'regional',queried_at:'2026-09-30T01:01:00+00:00'};expect(detail({...base,report:d},actor,'regional',d.operation_id)).toEqual(d);expect(()=>queue({...base,view:'pending',items:[d,d],next_after_id:null},actor,'regional','pending')).toThrow();expect(()=>detail({...base,person_id:id(90),report:d},actor,'regional',d.operation_id)).toThrow();expect(()=>report({...d,lines:[{...d.lines[0],quantity:'2.000'}]})).toThrow();});
it('matches Python canonical UTF-8 hashing with internal unicode and JSON controls',async()=>{const value={operation_id:id(2),expected_submission_plan_hash:'a'.repeat(64),comment:'核实🙂\n\t内部\u0085空白'};expect(await hash(value)).toBe('0ca98fbcd4c584d458982138dfb701172329418258ef54ef4936eb62fe1d9cf6');});
it.each(['\u0085边界','边界\u001c','\u3000边界','\ud800'])('rejects Python-invalid comments %s',async comment=>{await expect(prepare(actor,'regional',document(),comment)).rejects.toThrow();});

it('changed authority scope during readback retains the exact pending command',async()=>{const w=await world();await w.save();w.setResult(found(w.p));let calls=0;w.transport.context=async()=>({...actor,stage:'regional',authority_hash:(++calls===1?'a':'b').repeat(64),can_read:true,can_write:true});await expect(recover(w.transport,w.store,w.p)).rejects.toThrow();expect(w.store.list(actor.person_id)).toEqual([w.p]);});
it('a failed storage cleanup blocks further writes after successful proof',async()=>{const w=await world();await w.save();w.setResult(found(w.p));w.storage.removeItem=()=>{throw new Error();};await expect(recover(w.transport,w.store,w.p)).rejects.toThrow();await expect(submit(w.transport,w.store,w.p)).rejects.toThrow();expect(w.transport.submit).not.toHaveBeenCalled();});
