import { type FormalMaterialRequestAdapter, validateFormalMaterialRequestAccess, validateFormalMaterialRequestFreshIdentity } from "./formalMaterialRequestAdapter";
import { validateMaterialRequestDetail } from "./formalMaterialRequests";
import { type ReceiptInput, type ReceiptResult, validateReceiptInput, validateReceiptResult } from "./materialRequestShipment";

export type ReceiptCommandStatus = Readonly<{ schema_version: "1.0"; lookup_status: "confirmed" | "not_observed"; request_hash: string | null; command: ReceiptResult | null }>;
function exact(value: unknown, keys: readonly string[]): Record<string, unknown> { if (!value || typeof value !== "object" || Array.isArray(value) || JSON.stringify(Object.keys(value).sort()) !== JSON.stringify([...keys].sort())) throw new Error("收货核验记录字段无效"); return value as Record<string, unknown>; }
export function validateReceiptCommandStatus(value: unknown): ReceiptCommandStatus {
  const row = exact(value, ["schema_version", "lookup_status", "request_hash", "command"]);
  if (row.schema_version !== "1.0") throw new Error("收货核验响应版本无效");
  if (row.lookup_status === "not_observed" && row.request_hash === null && row.command === null) return { schema_version: "1.0", lookup_status: "not_observed", request_hash: null, command: null };
  if (row.lookup_status !== "confirmed" || typeof row.request_hash !== "string" || !/^[a-f0-9]{64}$/.test(row.request_hash)) throw new Error("收货核验响应无效");
  const command = validateReceiptResult(row.command); if (!command.idempotency_replayed) throw new Error("收货历史标记无效");
  return { schema_version: "1.0", lookup_status: "confirmed", request_hash: row.request_hash, command };
}
const UUID = /^(?!00000000-0000-0000-0000-000000000000$)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const COORDINATE = /^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/;
export type ReceiptSentinel = Readonly<{ v: 1; kind: "receipt"; trace: string; key: string; person_id: string; authorization_version: number; request_id: string; input: ReceiptInput }>;
export function validateReceiptSentinel(value: unknown): ReceiptSentinel { const r = exact(value, ["v","kind","trace","key","person_id","authorization_version","request_id","input"]); if (r.v !== 1 || r.kind !== "receipt" || typeof r.trace !== "string" || !COORDINATE.test(r.trace) || typeof r.key !== "string" || !COORDINATE.test(r.key) || typeof r.person_id !== "string" || !UUID.test(r.person_id) || typeof r.request_id !== "string" || !UUID.test(r.request_id) || !Number.isSafeInteger(r.authorization_version) || Number(r.authorization_version) < 1) throw new Error("原收货请求坐标无效"); return { v:1, kind:"receipt", trace:r.trace, key:r.key, person_id:r.person_id, authorization_version:r.authorization_version as number, request_id:r.request_id, input:validateReceiptInput(r.input) }; }
type Read = { kind: "missing"|"corrupt"|"unavailable" } | { kind:"valid"; value:ReceiptSentinel };
export type ReceiptStore = Readonly<{ read:()=>Read; persist:(value:ReceiptSentinel)=>void; clear:(trace:string)=>void }>;
export function createReceiptStore(storage?: Pick<Storage,"getItem"|"setItem"|"removeItem">): ReceiptStore { const key="cloud-oam-material-request-receipt-v1", target=()=>storage??window.localStorage; let fault=false; const read=():Read=>{if(fault)return {kind:"unavailable"};let raw:string|null;try{raw=target().getItem(key)}catch{fault=true;return {kind:"unavailable"}}if(raw===null)return {kind:"missing"};try{return {kind:"valid",value:validateReceiptSentinel(JSON.parse(raw))}}catch{return {kind:"corrupt"}}};return {read,persist(value){const checked=validateReceiptSentinel(value);if(read().kind!=="missing")throw new Error("已有待核验收货，禁止覆盖原请求");try{target().setItem(key,JSON.stringify(checked))}catch{fault=true;throw new Error("无法保存收货核验记录，提交已停止")}const saved=read();if(saved.kind!=="valid"||JSON.stringify(saved.value)!==JSON.stringify(checked)){fault=true;throw new Error("收货核验记录未可靠保存，提交已停止")}},clear(trace){const current=read();if(current.kind!=="valid"||current.value.trace!==trace)throw new Error("原收货坐标已变化，禁止清理");try{target().removeItem(key)}catch{fault=true;throw new Error("收货核验记录清理失败")}if(read().kind!=="missing"){fault=true;throw new Error("收货核验记录清理失败")}}}; }
function ordered(value: unknown): unknown { return Array.isArray(value)?value.map(ordered):value&&typeof value==="object"?Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,ordered(v)])):value; }
export async function receiptRequestHash(requestId:string,input:ReceiptInput):Promise<string>{const checked=validateReceiptInput(input);const payload={request_id:requestId.toLowerCase(),version:checked.expected_request_version,receiver:checked.receiver_person_id.toLowerCase(),at:checked.received_at,lines:checked.lines.map(x=>({id:x.shipment_line_id.toLowerCase(),a:x.accepted_qty,r:x.rejected_qty,condition:x.condition,serials:x.serial_ids.map(s=>s.toLowerCase()).sort(),evidence:x.exception_evidence_file_id?.toLowerCase()??null}))};const encoded=JSON.stringify(ordered(payload)).replace(/[\u007f-\uffff]/g,c=>`\\u${c.charCodeAt(0).toString(16).padStart(4,"0")}`);const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(encoded));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("");}
type RecoveryAdapter = FormalMaterialRequestAdapter & Required<Pick<FormalMaterialRequestAdapter,"loadIdentityNoReplay"|"loadAccessNoReplay"|"detailNoReplay"|"receiptCommandStatusNoReplay">>;
export function hasReceiptRecovery(adapter:FormalMaterialRequestAdapter):adapter is RecoveryAdapter{return [adapter.loadIdentityNoReplay,adapter.loadAccessNoReplay,adapter.detailNoReplay,adapter.receiptCommandStatusNoReplay].every(x=>typeof x==="function");}
export async function recoverReceipt(adapter:RecoveryAdapter,store:ReceiptStore,original:ReceiptSentinel,canCommit=()=>true){const sentinel=validateReceiptSentinel(original);const identity=validateFormalMaterialRequestFreshIdentity(await adapter.loadIdentityNoReplay());const access=validateFormalMaterialRequestAccess(await adapter.loadAccessNoReplay());if(identity.person_id!==sentinel.person_id||identity.authorization_version!==sentinel.authorization_version||access.person_id!==sentinel.person_id||access.authorization_version!==sentinel.authorization_version||!access.can_read)throw new Error("收货身份或权限已变化，保留原请求");const status=validateReceiptCommandStatus(await adapter.receiptCommandStatusNoReplay(sentinel.request_id,sentinel.key));if(!status.command||status.lookup_status!=="confirmed")throw new Error("尚未观察到原收货结果，继续保留请求；不能据此再次提交");if(status.request_hash!==await receiptRequestHash(sentinel.request_id,sentinel.input))throw new Error("原收货请求内容指纹不一致，暂停处理");const detail=validateMaterialRequestDetail(await adapter.detailNoReplay(sentinel.request_id),sentinel.request_id);if(detail.request_version<sentinel.input.expected_request_version)throw new Error("需求回读版本落后，保留原请求");const afterIdentity=validateFormalMaterialRequestFreshIdentity(await adapter.loadIdentityNoReplay());const afterAccess=validateFormalMaterialRequestAccess(await adapter.loadAccessNoReplay());if(JSON.stringify(identity)!==JSON.stringify(afterIdentity)||JSON.stringify(access)!==JSON.stringify(afterAccess)||!canCommit())throw new Error("核验期间身份、权限或页面已变化，保留原请求");const stored=store.read();if(stored.kind!=="valid"||JSON.stringify(stored.value)!==JSON.stringify(sentinel))throw new Error("原收货记录已变化，禁止清理");store.clear(sentinel.trace);return {command:status.command,detail};}
