import { type FormalMaterialRequestAdapter, validateFormalMaterialRequestAccess, validateFormalMaterialRequestFreshIdentity } from "./formalMaterialRequestAdapter";
import { type InboundOrderResult, validateInboundOrderResult } from "./materialRequestShipment";
const UUID=/^(?!00000000-0000-0000-0000-000000000000$)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const COORDINATE=/^[A-Za-z0-9][A-Za-z0-9._:-]{15,127}$/;
export type InboundSentinel=Readonly<{v:1;kind:"inbound-create"|"inbound-post";trace:string;key:string|null;person_id:string;authorization_version:number;request_id:string;expected_version:number;receipt_id:string;target_location_id:string;target_person_id:string;inbound_order_id?:string}>;
function exact(v:unknown,keys:string[]){if(!v||typeof v!=="object"||Array.isArray(v)||JSON.stringify(Object.keys(v).sort())!==JSON.stringify([...keys].sort()))throw new Error("入账核验记录字段无效");return v as Record<string,unknown>}
export function validateInboundSentinel(v:unknown):InboundSentinel{const r=exact(v,["v","kind","trace","key","person_id","authorization_version","request_id","expected_version","receipt_id","target_location_id","target_person_id",...(v&&typeof v==="object"&&"inbound_order_id" in v?["inbound_order_id"]:[])]);if(r.v!==1||(r.kind!=="inbound-create"&&r.kind!=="inbound-post")||typeof r.trace!=="string"||!COORDINATE.test(r.trace)||(r.key!==null&&(typeof r.key!=="string"||!COORDINATE.test(r.key)))||typeof r.person_id!=="string"||!UUID.test(r.person_id)||typeof r.request_id!=="string"||!UUID.test(r.request_id)||!Number.isSafeInteger(r.expected_version)||Number(r.expected_version)<1||typeof r.receipt_id!=="string"||!UUID.test(r.receipt_id)||typeof r.target_location_id!=="string"||!UUID.test(r.target_location_id)||typeof r.target_person_id!=="string"||!UUID.test(r.target_person_id)||(r.kind==="inbound-post"&&(typeof r.inbound_order_id!=="string"||!UUID.test(r.inbound_order_id))))throw new Error("原入账请求坐标无效");return r as InboundSentinel}
type Read={kind:"missing"|"corrupt"|"unavailable"}|{kind:"valid";value:InboundSentinel};
export type InboundStore=Readonly<{read:()=>Read;persist:(v:InboundSentinel)=>void;clear:(trace:string)=>void}>;
export function createInboundStore(storage?:Pick<Storage,"getItem"|"setItem"|"removeItem">):InboundStore{const key="cloud-oam-material-request-inbound-v1",target=()=>storage??window.localStorage;let fault=false;const read=():Read=>{if(fault)return{kind:"unavailable"};let raw:string|null;try{raw=target().getItem(key)}catch{fault=true;return{kind:"unavailable"}}if(raw===null)return{kind:"missing"};try{return{kind:"valid",value:validateInboundSentinel(JSON.parse(raw))}}catch{return{kind:"corrupt"}}};return{read,persist(v){const checked=validateInboundSentinel(v);if(read().kind!=="missing")throw new Error("已有待核验入账，禁止覆盖原请求");try{target().setItem(key,JSON.stringify(checked))}catch{fault=true;throw new Error("无法保存入账核验记录，提交已停止")}if(read().kind!=="valid")throw new Error("入账核验记录未可靠保存，提交已停止")},clear(trace){const current=read();if(current.kind!=="valid"||current.value.trace!==trace)throw new Error("原入账坐标已变化，禁止清理");try{target().removeItem(key)}catch{fault=true;throw new Error("入账核验记录清理失败")}if(read().kind!=="missing")throw new Error("入账核验记录清理失败")}}}
type RecoveryAdapter=FormalMaterialRequestAdapter&Required<Pick<FormalMaterialRequestAdapter,"loadIdentityNoReplay"|"loadAccessNoReplay"|"listInboundOrders">>;
export function hasInboundRecovery(a:FormalMaterialRequestAdapter):a is RecoveryAdapter{return [a.loadIdentityNoReplay,a.loadAccessNoReplay,a.listInboundOrders].every(x=>typeof x==="function")}
export async function recoverInbound(adapter:RecoveryAdapter,store:InboundStore,s:InboundSentinel){const identity=validateFormalMaterialRequestFreshIdentity(await adapter.loadIdentityNoReplay()),access=validateFormalMaterialRequestAccess(await adapter.loadAccessNoReplay());if(identity.person_id!==s.person_id||identity.authorization_version!==s.authorization_version||access.person_id!==s.person_id||access.authorization_version!==s.authorization_version||!access.can_read)throw new Error("入账身份或权限已变化，保留原请求");const rows=(await adapter.listInboundOrders(s.request_id)).map(validateInboundOrderResult);const found=rows.find(x=>x.inbound_order_id.toLowerCase()===s.inbound_order_id?.toLowerCase()||x.receipt_id.toLowerCase()===s.receipt_id.toLowerCase());if(!found)throw new Error("尚未观察到原入账结果，继续保留请求；不能据此再次提交");if(found.receipt_id.toLowerCase()!==s.receipt_id.toLowerCase()||found.target_location_id.toLowerCase()!==s.target_location_id.toLowerCase()||found.target_person_id.toLowerCase()!==s.target_person_id.toLowerCase())throw new Error("入账结果与原收货目标不一致，保留原请求");store.clear(s.trace);return found}
