const UUID=/^(?!00000000-0000-0000-0000-000000000000$)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const DECIMAL=/^(?:0|[1-9]\d{0,14})\.\d{3}$/;
const RECEIPT_CONDITIONS=["normal","shortage","damaged","wrong_material","wrong_serial","rejected"] as const;
function id(v:unknown):string { if(typeof v!=="string"||!UUID.test(v)) throw new Error("发运坐标无效"); return v; }
function text(v:unknown,max=100):string { if(typeof v!=="string"||!v||v!==v.trim()||v.length>max||/[\x00-\x1f\x7f]/.test(v)) throw new Error("发运文本无效"); return v; }
function exact(v:unknown, keys:string[]):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v)||Object.keys(v as object).sort().join()!=keys.slice().sort().join())throw new Error("发运响应字段不完整");return v as Record<string,unknown>}
export type ShipmentLineInput=Readonly<{outbound_posting_id:string;shipped_qty:string;serial_ids:readonly string[]}>;
export type ShipmentInput=Readonly<{expected_request_version:number;target_location_id:string;target_person_id:string|null;carrier:string;tracking_no:string;shipped_at:string;lines:readonly ShipmentLineInput[]}>;
export type ShipmentLineResult=Readonly<{shipment_line_id:string;outbound_posting_id:string;shipped_qty:string;serial_ids:readonly string[]}>;
export type ShipmentResult=Readonly<{schema_version:"1.0";shipment_id:string;shipment_no:string;request_id:string;status:string;target_location_id:string;target_person_id:string|null;carrier:string;tracking_no:string;shipped_at:string;lines:readonly ShipmentLineResult[];idempotency_replayed:boolean}>;
export type ShipmentOption=Readonly<{posting_id:string;posting_no:string;outbound_line_id:string;pick_id:string;posted_qty:string;shipped_qty:string;shippable_qty:string;serial_ids:readonly string[];serials:readonly {serial_id:string;serial_no:string}[]}>;
export type ShipmentOptions=Readonly<{request_id:string;request_version:number;items:readonly ShipmentOption[]}>;
export type InboundOrderInput=Readonly<{expected_request_version:number;receipt_id:string;target_location_id:string;target_person_id:string}>;
export type InboundOrderResult=Readonly<{schema_version:"1.0";inbound_order_id:string;inbound_no:string;receipt_id:string;target_location_id:string;target_person_id:string;status:string;posting_transaction_id:string|null}>;
export type InboundPostingResult=Readonly<{schema_version:"1.0";inbound_order_id:string;inventory_transaction_id:string;replayed:boolean}>;
export type LogisticsEventResult=Readonly<{schema_version:"1.0";event_id:string;shipment_id:string;event_type:string;event_at:string;source:string;evidence_file_id:string|null;external_ref:string|null;idempotency_replayed:boolean}>;
export type LogisticsEventInput=Readonly<{event_type:"pickup"|"transit"|"signed"|"exception";event_at:string;source:string;evidence_file_id:string|null;external_ref:string|null}>;
export type ReceiptInput=Readonly<{expected_request_version:number;receiver_person_id:string;received_at:string;lines:readonly {shipment_line_id:string;accepted_qty:string;rejected_qty:string;condition:string;serial_ids:readonly string[];exception_evidence_file_id:string|null}[]}>;
export type ReceiptResult=Readonly<{schema_version:"1.0";receipt_id:string;receipt_no:string;shipment_id:string;status:string;lines:readonly Record<string,unknown>[];exceptions:readonly Record<string,unknown>[];idempotency_replayed:boolean}>;
export function validateInboundOrderInput(v:unknown):InboundOrderInput{const r=exact(v,["expected_request_version","receipt_id","target_location_id","target_person_id"]);if(!Number.isSafeInteger(r.expected_request_version)||Number(r.expected_request_version)<1)throw new Error("入账版本无效");return {expected_request_version:r.expected_request_version as number,receipt_id:id(r.receipt_id),target_location_id:id(r.target_location_id),target_person_id:id(r.target_person_id)};}
export function validateReceiptInput(v:unknown):ReceiptInput{const r=exact(v,["expected_request_version","receiver_person_id","received_at","lines"]);if(!Number.isSafeInteger(r.expected_request_version)||!Array.isArray(r.lines)||r.lines.length<1||typeof r.received_at!=="string"||!Number.isFinite(Date.parse(r.received_at)))throw new Error("收货输入无效");return {expected_request_version:r.expected_request_version as number,receiver_person_id:id(r.receiver_person_id),received_at:text(r.received_at,64),lines:Object.freeze(r.lines.map(x=>{const q=exact(x,["shipment_line_id","accepted_qty","rejected_qty","condition","serial_ids","exception_evidence_file_id"]);if(typeof q.accepted_qty!=="string"||typeof q.rejected_qty!=="string"||!DECIMAL.test(q.accepted_qty)||!DECIMAL.test(q.rejected_qty)||Number(q.accepted_qty)<0||Number(q.rejected_qty)<0||!Array.isArray(q.serial_ids)||typeof q.exception_evidence_file_id!=="string"&&q.exception_evidence_file_id!==null||typeof q.condition!=="string"||!RECEIPT_CONDITIONS.includes(q.condition as typeof RECEIPT_CONDITIONS[number]))throw new Error("收货明细无效");return {shipment_line_id:id(q.shipment_line_id),accepted_qty:q.accepted_qty,rejected_qty:q.rejected_qty,condition:q.condition,serial_ids:Object.freeze(q.serial_ids.map(id)),exception_evidence_file_id:q.exception_evidence_file_id===null?null:id(q.exception_evidence_file_id)};}))};}
export function validateReceiptResult(v:unknown):ReceiptResult{const r=exact(v,["schema_version","receipt_id","receipt_no","shipment_id","status","lines","exceptions","idempotency_replayed"]);if(r.schema_version!=="1.0"||typeof r.idempotency_replayed!=="boolean"||!Array.isArray(r.lines)||!Array.isArray(r.exceptions))throw new Error("收货响应无效");return {schema_version:"1.0",receipt_id:id(r.receipt_id),receipt_no:text(r.receipt_no),shipment_id:id(r.shipment_id),status:text(r.status,32),lines:Object.freeze(r.lines as Record<string,unknown>[]),exceptions:Object.freeze(r.exceptions as Record<string,unknown>[]),idempotency_replayed:r.idempotency_replayed};}
export function validateLogisticsEventInput(v:unknown):LogisticsEventInput{const r=exact(v,["event_type","event_at","source","evidence_file_id","external_ref"]);if(!["pickup","transit","signed","exception"].includes(String(r.event_type))||typeof r.evidence_file_id!=="string"&&r.evidence_file_id!==null||typeof r.external_ref!=="string"&&r.external_ref!==null)throw new Error("物流事件输入无效");return {event_type:r.event_type as LogisticsEventInput["event_type"],event_at:text(r.event_at,64),source:text(r.source,32),evidence_file_id:r.evidence_file_id===null?null:id(r.evidence_file_id),external_ref:r.external_ref===null?null:text(r.external_ref,200)};}
export function validateLogisticsEventResult(v:unknown):LogisticsEventResult{const r=exact(v,["schema_version","event_id","shipment_id","event_type","event_at","source","evidence_file_id","external_ref","idempotency_replayed"]);if(r.schema_version!=="1.0"||typeof r.idempotency_replayed!=="boolean"||!['pickup','transit','signed','exception'].includes(String(r.event_type))||typeof r.evidence_file_id!=="string"&&r.evidence_file_id!==null||typeof r.external_ref!=="string"&&r.external_ref!==null)throw new Error("物流事件响应无效");return {schema_version:"1.0",event_id:id(r.event_id),shipment_id:id(r.shipment_id),event_type:String(r.event_type),event_at:text(r.event_at,64),source:text(r.source,32),evidence_file_id:r.evidence_file_id===null?null:id(r.evidence_file_id),external_ref:r.external_ref===null?null:text(r.external_ref,200),idempotency_replayed:r.idempotency_replayed};}
export function validateInboundOrderResult(v:unknown):InboundOrderResult{const r=exact(v,["schema_version","inbound_order_id","inbound_no","receipt_id","target_location_id","target_person_id","status","posting_transaction_id"]);if(r.schema_version!=="1.0"||typeof r.posting_transaction_id!=="string"&&r.posting_transaction_id!==null)throw new Error("入账单响应版本无效");return {schema_version:"1.0",inbound_order_id:id(r.inbound_order_id),inbound_no:text(r.inbound_no),receipt_id:id(r.receipt_id),target_location_id:id(r.target_location_id),target_person_id:id(r.target_person_id),status:text(r.status,32),posting_transaction_id:r.posting_transaction_id===null?null:id(r.posting_transaction_id)};}
export function validateInboundPostingResult(v:unknown):InboundPostingResult{const r=exact(v,["schema_version","inbound_order_id","inventory_transaction_id","replayed"]);if(r.schema_version!=="1.0"||typeof r.replayed!=="boolean")throw new Error("入账过账响应无效");return {schema_version:"1.0",inbound_order_id:id(r.inbound_order_id),inventory_transaction_id:id(r.inventory_transaction_id),replayed:r.replayed};}
export function validateShipmentOptions(v:unknown):ShipmentOptions{const r=exact(v,["request_id","request_version","items"]);if(!Array.isArray(r.items)||!Number.isSafeInteger(r.request_version))throw new Error("发运候选响应无效");return {request_id:id(r.request_id),request_version:r.request_version as number,items:Object.freeze(r.items.map(x=>{const q=exact(x,["posting_id","posting_no","outbound_line_id","pick_id","posted_qty","shipped_qty","shippable_qty","serial_ids","serials"]);const serial_ids=(q.serial_ids as unknown[]).map(id);if(!Array.isArray(q.serials)||serial_ids.length!==q.serials.length)throw new Error("发运候选 SN 无效");return {posting_id:id(q.posting_id),posting_no:text(q.posting_no),outbound_line_id:id(q.outbound_line_id),pick_id:id(q.pick_id),posted_qty:text(q.posted_qty,32),shipped_qty:text(q.shipped_qty,32),shippable_qty:text(q.shippable_qty,32),serial_ids:Object.freeze(serial_ids),serials:Object.freeze((q.serials as unknown[]).map(s=>{const z=exact(s,["serial_id","serial_no"]);return {serial_id:id(z.serial_id),serial_no:text(z.serial_no,200)}}))};}))};}
export function validateShipmentInput(v:unknown):ShipmentInput{const r=exact(v,["expected_request_version","target_location_id","target_person_id","carrier","tracking_no","shipped_at","lines"]);if(!Number.isSafeInteger(r.expected_request_version)||Number(r.expected_request_version)<1||!Array.isArray(r.lines)||r.lines.length<1||r.lines.length>100)throw new Error("发运版本或明细无效");const ids=new Set<string>();const lines=r.lines.map(x=>{const l=exact(x,["outbound_posting_id","shipped_qty","serial_ids"]);const posting=id(l.outbound_posting_id), serials=l.serial_ids;if(ids.has(posting)||!Array.isArray(serials)||serials.length>1000)throw new Error("发运明细重复或 SN 无效");ids.add(posting);if(typeof l.shipped_qty!=="string"||!DECIMAL.test(l.shipped_qty)||Number(l.shipped_qty)<=0)throw new Error("发运数量必须保留三位小数");const ss=serials.map(id);if(new Set(ss).size!==ss.length)throw new Error("发运 SN 重复");return {outbound_posting_id:posting,shipped_qty:l.shipped_qty,serial_ids:Object.freeze(ss)};});const at=text(r.shipped_at,50);if(!Number.isFinite(Date.parse(at)))throw new Error("交运时间无效");return {expected_request_version:r.expected_request_version as number,target_location_id:id(r.target_location_id),target_person_id:r.target_person_id===null?null:id(r.target_person_id),carrier:text(r.carrier),tracking_no:text(r.tracking_no),shipped_at:at,lines:Object.freeze(lines)};}
export function validateShipmentResult(v:unknown):ShipmentResult{const r=exact(v,["schema_version","shipment_id","shipment_no","request_id","status","target_location_id","target_person_id","carrier","tracking_no","shipped_at","lines","idempotency_replayed"]);if(r.schema_version!=="1.0"||!['pending_handover','shipped','in_transit','exception'].includes(String(r.status))||typeof r.idempotency_replayed!=="boolean"||!Array.isArray(r.lines)||typeof r.target_person_id!=="string"&&r.target_person_id!==null)throw new Error("发运响应状态无效");return {schema_version:"1.0",shipment_id:id(r.shipment_id),shipment_no:text(r.shipment_no),request_id:id(r.request_id),status:String(r.status),target_location_id:id(r.target_location_id),target_person_id:r.target_person_id===null?null:id(r.target_person_id),carrier:text(r.carrier),tracking_no:text(r.tracking_no),shipped_at:text(r.shipped_at,50),lines:Object.freeze(r.lines.map(x=>{const q=exact(x,["shipment_line_id","outbound_posting_id","shipped_qty","serial_ids"]);if(typeof q.shipped_qty!=="string"||!DECIMAL.test(q.shipped_qty)||!Array.isArray(q.serial_ids))throw new Error("发运响应明细无效");const serials=(q.serial_ids as unknown[]).map(id);if(new Set(serials).size!==serials.length)throw new Error("发运响应 SN 重复");return {shipment_line_id:id(q.shipment_line_id),outbound_posting_id:id(q.outbound_posting_id),shipped_qty:q.shipped_qty,serial_ids:Object.freeze(serials)};})),idempotency_replayed:r.idempotency_replayed};}
