const UUID=/^(?!00000000-0000-0000-0000-000000000000$)[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const DECIMAL=/^(?:0|[1-9]\d{0,14})\.\d{3}$/;
function id(v:unknown):string { if(typeof v!=="string"||!UUID.test(v)) throw new Error("发运坐标无效"); return v; }
function text(v:unknown,max=100):string { if(typeof v!=="string"||!v||v!==v.trim()||v.length>max||/[\x00-\x1f\x7f]/.test(v)) throw new Error("发运文本无效"); return v; }
function exact(v:unknown, keys:string[]):Record<string,unknown>{if(!v||typeof v!=="object"||Array.isArray(v)||Object.keys(v as object).sort().join()!=keys.slice().sort().join())throw new Error("发运响应字段不完整");return v as Record<string,unknown>}
export type ShipmentLineInput=Readonly<{outbound_posting_id:string;shipped_qty:string;serial_ids:readonly string[]}>;
export type ShipmentInput=Readonly<{expected_request_version:number;target_location_id:string;target_person_id:string|null;carrier:string;tracking_no:string;shipped_at:string;lines:readonly ShipmentLineInput[]}>;
export type ShipmentResult=Readonly<{schema_version:"1.0";shipment_id:string;shipment_no:string;request_id:string;status:string;carrier:string;tracking_no:string;shipped_at:string;lines:readonly ShipmentLineInput[];idempotency_replayed:boolean}>;
export type ShipmentOption=Readonly<{posting_id:string;posting_no:string;outbound_line_id:string;pick_id:string;posted_qty:string;shipped_qty:string;shippable_qty:string;serial_ids:readonly string[];serials:readonly {serial_id:string;serial_no:string}[]}>;
export type ShipmentOptions=Readonly<{request_id:string;request_version:number;items:readonly ShipmentOption[]}>;
export function validateShipmentOptions(v:unknown):ShipmentOptions{const r=exact(v,["request_id","request_version","items"]);if(!Array.isArray(r.items)||!Number.isSafeInteger(r.request_version))throw new Error("发运候选响应无效");return {request_id:id(r.request_id),request_version:r.request_version as number,items:Object.freeze(r.items.map(x=>{const q=exact(x,["posting_id","posting_no","outbound_line_id","pick_id","posted_qty","shipped_qty","shippable_qty","serial_ids","serials"]);const serial_ids=(q.serial_ids as unknown[]).map(id);if(!Array.isArray(q.serials)||serial_ids.length!==q.serials.length)throw new Error("发运候选 SN 无效");return {posting_id:id(q.posting_id),posting_no:text(q.posting_no),outbound_line_id:id(q.outbound_line_id),pick_id:id(q.pick_id),posted_qty:text(q.posted_qty,32),shipped_qty:text(q.shipped_qty,32),shippable_qty:text(q.shippable_qty,32),serial_ids:Object.freeze(serial_ids),serials:Object.freeze((q.serials as unknown[]).map(s=>{const z=exact(s,["serial_id","serial_no"]);return {serial_id:id(z.serial_id),serial_no:text(z.serial_no,200)}}))};}))};}
export function validateShipmentInput(v:unknown):ShipmentInput{const r=exact(v,["expected_request_version","target_location_id","target_person_id","carrier","tracking_no","shipped_at","lines"]);if(!Number.isSafeInteger(r.expected_request_version)||Number(r.expected_request_version)<1||!Array.isArray(r.lines)||r.lines.length<1||r.lines.length>100)throw new Error("发运版本或明细无效");const ids=new Set<string>();const lines=r.lines.map(x=>{const l=exact(x,["outbound_posting_id","shipped_qty","serial_ids"]);const posting=id(l.outbound_posting_id), serials=l.serial_ids;if(ids.has(posting)||!Array.isArray(serials)||serials.length>1000)throw new Error("发运明细重复或 SN 无效");ids.add(posting);if(typeof l.shipped_qty!=="string"||!DECIMAL.test(l.shipped_qty)||Number(l.shipped_qty)<=0)throw new Error("发运数量必须保留三位小数");const ss=serials.map(id);if(new Set(ss).size!==ss.length)throw new Error("发运 SN 重复");return {outbound_posting_id:posting,shipped_qty:l.shipped_qty,serial_ids:Object.freeze(ss)};});const at=text(r.shipped_at,50);if(!Number.isFinite(Date.parse(at)))throw new Error("交运时间无效");return {expected_request_version:r.expected_request_version as number,target_location_id:id(r.target_location_id),target_person_id:r.target_person_id===null?null:id(r.target_person_id),carrier:text(r.carrier),tracking_no:text(r.tracking_no),shipped_at:at,lines:Object.freeze(lines)};}
export function validateShipmentResult(v:unknown):ShipmentResult{const r=exact(v,["schema_version","shipment_id","shipment_no","request_id","status","carrier","tracking_no","shipped_at","lines","idempotency_replayed"]);if(r.schema_version!=="1.0"||!['pending_handover','shipped','in_transit','exception'].includes(String(r.status))||typeof r.idempotency_replayed!=="boolean"||!Array.isArray(r.lines))throw new Error("发运响应状态无效");return {schema_version:"1.0",shipment_id:id(r.shipment_id),shipment_no:text(r.shipment_no),request_id:id(r.request_id),status:String(r.status),carrier:text(r.carrier),tracking_no:text(r.tracking_no),shipped_at:text(r.shipped_at,50),lines:Object.freeze(r.lines.map(x=>validateShipmentInput({expected_request_version:1,target_location_id:"11111111-1111-1111-1111-111111111111",target_person_id:null,carrier:"x",tracking_no:"x",shipped_at:"2026-01-01T00:00:00Z",lines:[x]}).lines[0])),idempotency_replayed:r.idempotency_replayed};}
