import { vi } from "vitest";
import { approvedDetail, identity, access } from "./materialRequestReservationTestFixtures";
import { commandHash, type PersonalCommand, type ReceiptCandidate, type ReceivingPage, type InboundPage } from "./myFulfillmentContract";
import { createPersonalStore, type PersonalPending } from "./myFulfillmentRecovery";
export const sid = "80000000-0000-4000-8000-000000000001", slid = "80000000-0000-4000-8000-000000000002", receiptId = "80000000-0000-4000-8000-000000000003", tx = "80000000-0000-4000-8000-000000000004";
export const detail = approvedDetail(), personId = identity().person_id;
const anchor = { schema_version: "1.0" as const, request_id: detail.request_id, request_no: detail.request_no, request_version: detail.request_version, person_id: personId };
export const candidate: ReceiptCandidate = { ...anchor, shipment_id: sid, shipment_no: "SHP-TEST-1", shipped_at: "2026-01-01T00:00:00Z", target_location_name: "本人个人仓", checked_at: "2026-01-02T00:00:00Z", can_receive: true, blocked_reason: null,
  lines: [{ shipment_line_id: slid, request_line_id: detail.lines[0].request_line_id, sku_code: "SKU-1", material_name: "测试备件", base_unit: "件", shipped_qty: "2.000", accepted_qty: "0.000", rejected_qty: "0.000", unconfirmed_qty: "2.000", has_exception: false, lot_no: null, tracking_mode: "none", quantity_scale: 0, allow_fraction: false, remaining_serials: [] }] };
const { lot_no: _lot, tracking_mode: _mode, quantity_scale: _scale, allow_fraction: _fraction, remaining_serials: _serials, ...packageLine } = candidate.lines[0];
export const packages: ReceivingPage = { ...anchor, next_after_id: null, packages: [{ shipment_id: sid, shipment_no: "SHP-TEST-1", shipment_status: "shipped", carrier: "合成承运商", tracking_no: "TEST-001", shipped_at: candidate.shipped_at, target_location_id: sid, target_location_name: "本人个人仓", lines: [packageLine] }] };
export const inbounds: InboundPage = { ...anchor, can_post: true, next_after_id: null, items: [{ receipt_id: receiptId, status: "pending", message: "等待本人确认入账", detail: { receipt_no: "RCT-TEST-1", receipt_request_hash: "ab".repeat(32), shipment_id: sid, shipment_no: "SHP-TEST-1", target_location_name: "本人个人仓", received_at: "2026-01-03T00:00:00Z", lines: [{ receipt_line_id: slid, sku_code: "SKU-1", material_name: "测试备件", base_unit: "件", accepted_qty: "1.000", rejected_qty: "0.000", condition: "normal", tracking_mode: "none", rejected_serials: [], accepted_serials: [] }], inbound_no: null, inventory_transaction_id: null, posted_at: null } }] };
export const receiptCommand: PersonalCommand = { kind: "receipt", input: { expected_request_version: detail.request_version, shipment_id: sid, received_at: "2026-01-03T00:00:00.000Z", lines: [{ shipment_line_id: slid, accepted_qty: "1.000", rejected_qty: "0.000", condition: "normal", accepted_serial_ids: [], rejected_serial_ids: [], exception_evidence_file_id: null }] } };
export const inboundCommand: PersonalCommand = { kind: "inbound", input: { expected_request_version: detail.request_version, receipt_id: receiptId, receipt_request_hash: "ab".repeat(32) } };
export async function result(command: PersonalCommand) {
  const request_hash = await commandHash(detail.request_id, personId, command);
  return command.kind === "receipt" ? { schema_version: "1.0", request_id: detail.request_id, person_id: personId, receipt_id: receiptId, receipt_no: "RCT-TEST-1", shipment_id: sid, received_at: command.input.received_at, status: command.input.lines.every(x => x.condition === "normal") ? "accepted" : "exception", request_hash, lines: command.input.lines.map(line => ({ ...line, receipt_line_id: slid })), idempotency_replayed: false } : { schema_version: "1.0", request_id: detail.request_id, request_version: detail.request_version + 1, current_request_version: detail.request_version + 1, person_id: personId, receipt_id: receiptId, receipt_request_hash: command.input.receipt_request_hash, shipment_id: sid, inbound_order_id: sid, inbound_no: "INB-TEST-1", inventory_transaction_id: tx, posted_at: "2026-01-04T00:00:00Z", request_hash, idempotency_replayed: false };
}
export async function marker(command: PersonalCommand = receiptCommand): Promise<PersonalPending> { return { v: 1, request_id: detail.request_id, person_id: personId, authorization_version: identity().authorization_version, key: "personal-original-key-1234", trace: "personal-original-trace-1234", fingerprint: await commandHash(detail.request_id, personId, command), command }; }
export function props() {
  let last: PersonalCommand = receiptCommand;
  const personal = { packages: vi.fn(async () => structuredClone(packages)), receiptCandidate: vi.fn(async () => structuredClone(candidate)), inbounds: vi.fn(async () => structuredClone(inbounds)), submit: vi.fn(async (_: string, command: PersonalCommand) => { last = command; return result(command); }), status: vi.fn(async () => ({ schema_version: "1.0", lookup_status: "confirmed", command: { ...await result(last), idempotency_replayed: true } })), trace: vi.fn(async () => ({ schema_version: "1.0", lookup_status: "confirmed", command: { ...await result(last), idempotency_replayed: true } })) };
  const adapter = { personalFulfillment: personal, loadIdentityNoReplay: vi.fn(async () => identity()), loadAccessNoReplay: vi.fn(async () => ({ ...access(), schema_version: "1.0" as const })), detailNoReplay: vi.fn(async () => ({ ...detail, request_version: detail.request_version + 1 })) };
  return { adapter, detail, access: { ...access(), schema_version: "1.0" as const }, store: createPersonalStore(), onDetail: vi.fn(), onBlocking: vi.fn() };
}
