const assert = require('node:assert/strict')
const test = require('node:test')
function loadPage(stubs) {
  const saved=[]
  for (const [p,exports] of Object.entries(stubs)) { const r=require.resolve(p); saved.push([r,require.cache[r]]); require.cache[r]={id:r,filename:r,loaded:true,exports} }
  const pagePath=require.resolve('../pages/formal-operational-stocktake-detail/index'); delete require.cache[pagePath]
  let definition; global.Page=(v)=>{definition=v}; require(pagePath)
  return {definition,restore(){delete require.cache[pagePath]; for(const [r,e] of saved) e?require.cache[r]=e:delete require.cache[r]; delete global.Page}}
}
function instance(d){return Object.assign({},d,{data:JSON.parse(JSON.stringify(d.data)),setData(u){for(const [k,v] of Object.entries(u)){const parts=k.split('.');let t=this.data;while(parts.length>1){const x=parts.shift();t=t[x]||(t[x]={})}t[parts[0]]=v}}})}
const TASK='10000000-0000-4000-8000-000000000001', PERSON='40000000-0000-4000-8000-000000000001', ROUND='50000000-0000-4000-8000-000000000001'
const identity={person_id:PERSON,authorization_version:9}
function detail(){return {schema_version:'1.0',task_id:TASK,task_no:'ST-POST',task_type:'personal',region_org_id:'20000000-0000-4000-8000-000000000001',status:'approved',version:7,blind_count:true,current_round_no:1,posted_at:null,closed_at:null,allowed_actions:['post'],state_axes:{count_status:'submitted',difference_status:'evaluated',region_review_status:'approve',headquarters_review_status:'approve',recount_status:'not_required',posting_status:'not_posted',reconciliation_status:'not_reconciled',closure_status:'open'},close_control:{latest_reconciliation:null,close_completion:null},scopes:[],rounds:[{round_id:ROUND,round_no:1,round_type:'initial',status:'submitted',visible_differences:[],region_review:{decision:'approve'},headquarters_review:{decision:'approve'},posting:{status:'not_posted',posting_ids:[],posting_fact_count:0,visible_total_quantity:'0.000',covers_all_task_scopes:false,inventory_transaction_count:0,first_posted_at:null,last_posted_at:null},allowed_actions:[]} ]}}
function adapter(){return {countRecoveryMode:'legacy-test',reviewCommandStatus:()=>{},loadIdentityNoReplay:async()=>Object.assign({name:'N',employee_no:'E',organization_code:'HQ',organization_name:'HQ',account_status:'active',employment_status:'active',access_mode:'active',role_codes:['admin']},identity),loadAccessNoReplay:async()=>({schema_version:'1.0',person_id:PERSON,authorization_version:9,can_read:true,can_post:true}),detailNoReplay:async()=>detail(),postingCommandStatus:async()=>({}),execute:async()=>{}}}
function baseStubs(extra={}){return Object.assign({'../utils/session':{ensureLogin:()=>true},'../utils/formal-stocktake-adapter':{formalStocktakeAdapter:adapter(),createFormalStocktakeIntentRegistry:()=>({current:()=>null,begin(i){return Object.assign(i,{headers:{'X-Request-ID':'wx-post-page-0001'}})},complete(){}})},'../utils/formal-stocktake-post-recovery-store':{getFormalStocktakePostRecoveryStore:()=>({readPending:()=>({kind:'missing'})})},'../utils/formal-stocktake-post-recovery':{createFormalStocktakePostRecoveryAdapterFromFormalAdapter:()=>({}),recoverFormalStocktakePost:async()=>({detail:detail()}),submitDurableFormalStocktakePost:async()=>({detail:detail()}),FormalStocktakePostSubmissionPendingError:class extends Error{}},'../utils/formal-stocktake-count-recovery-store':{getFormalStocktakeCountRecoveryStore:()=>({readPending:()=>({kind:'missing'})})},'../utils/formal-stocktake-review-recovery-store':{getFormalStocktakeReviewRecoveryStore:()=>({readPending:()=>({kind:'missing'})})}},extra)}
test('real post button requires approved task and starts independent confirmation',()=>{const l=loadPage(baseStubs());try{const p=instance(l.definition);p._taskId=TASK;p._access=Object.assign({can_read:true,can_post:true},identity);p._detail=detail();p._intentRegistry={current:()=>null,begin(i){return i},complete(){}};p._postRecoveryStore={readPending:()=>({kind:'missing'})};p._countRecoveryStore={readPending:()=>({kind:'missing'})};p._reviewRecoveryStore={readPending:()=>({kind:'missing'})};p._hidden=false;p._writeLease=null;p.data.loading=false;p.openPostConfirm();assert.equal(p.data.postConfirm,true,p.data.errorMessage);assert.equal(p.data.terminalConfirm,'')}finally{l.restore()}})
test('persistent post marker blocks other writes and exposes read-only recovery',()=>{const marker={v:1,kind:'formal_stocktake_post',task_id:TASK,expected_task_version:7,actor_person_id:PERSON,actor_authorization_version:9,trace_request_id:'wx-post-page-0001'};const l=loadPage(baseStubs({'../utils/formal-stocktake-post-recovery-store':{getFormalStocktakePostRecoveryStore:()=>({readPending:()=>({kind:'valid',values:[marker]})})}}));try{const p=instance(l.definition);p._taskId=TASK;p._access=Object.assign({can_read:true,can_post:true},identity);p._detail=detail();p._intentRegistry={current:()=>null,begin(i){return i},complete(){}};p._postRecoveryStore={readPending:()=>({kind:'valid',values:[marker]})};p._countRecoveryStore={readPending:()=>({kind:'missing'})};p._reviewRecoveryStore={readPending:()=>({kind:'missing'})};p.data.loading=false;p.refreshPostRecovery();assert.equal(p.data.postRecoveryBlocked,true);assert.equal(p.data.postRecoveryCanCheck,true);let writes=0;p._writeLease=null;p.startTask();assert.equal(writes,0);p.onHide();assert.equal(p.data.postRecoveryBlocked,true);p._hidden=false;p.onUnload();assert.equal(p.data.postRecoveryBlocked,true)}finally{l.restore()}})
test('post confirmation cancels on identity drift before durable submission',async()=>{let submitted=0;const l=loadPage(baseStubs({'../utils/formal-stocktake-post-recovery':{submitDurableFormalStocktakePost:async()=>{submitted++;return {detail:detail()}},FormalStocktakePostSubmissionPendingError:class extends Error{}}}));try{const p=instance(l.definition);p._taskId=TASK;p._access=Object.assign({can_read:true,can_post:true},identity);p._detail=detail();p._intentRegistry={current:()=>null,begin(i){return i},complete(){}};p._postRecoveryStore={readPending:()=>({kind:'missing'})};p._countRecoveryStore={readPending:()=>({kind:'missing'})};p._reviewRecoveryStore={readPending:()=>({kind:'missing'})};p._hidden=false;p._writeLease=null;p.data.loading=false;p.openPostConfirm();p._access=Object.assign({can_read:true,can_post:true},{person_id:PERSON,authorization_version:10});await p.confirmPost();assert.equal(submitted,0);assert.match(p.data.errorMessage,/变化/)}finally{l.restore()}})

function postSealMarker() { return { v: 1, kind: 'formal_stocktake_post', task_id: TASK, expected_task_version: 7, actor_person_id: PERSON, actor_authorization_version: 9, trace_request_id: 'wx-post-page-0001' } }

test('permanent seal is exposed only for one durable marker bound to current posting authority',()=>{
  const marker = postSealMarker()
  const l = loadPage(baseStubs({
    '../utils/formal-stocktake-adapter': { formalStocktakeAdapter: Object.assign(adapter(), { sealPostingCommand: async () => ({}) }), createFormalStocktakeIntentRegistry: () => ({ current: () => null }) },
    '../utils/formal-stocktake-post-recovery-store': { getFormalStocktakePostRecoveryStore: () => ({ readPending: () => ({ kind: 'valid', values: [marker] }) }) }
  }))
  try {
    const p = instance(l.definition); p._taskId = TASK; p._access = Object.assign({ can_read: true, can_post: true }, identity); p._detail = detail(); p._postRecoveryStore = { readPending: () => ({ kind: 'valid', values: [marker] }) }; p._countRecoveryStore = { readPending: () => ({ kind: 'missing' }) }; p._reviewRecoveryStore = { readPending: () => ({ kind: 'missing' }) }; p._hidden = false; p.data.loading = false
    p.refreshPostRecovery(); assert.equal(p.data.postRecoveryCanSeal, true)
    p._access = Object.assign({ can_read: true, can_post: false }, identity); p.refreshPostRecovery(); assert.equal(p.data.postRecoveryCanSeal, false)
  } finally { l.restore() }
})

test('permanent seal clears the exact marker and refreshes after strict success',async()=>{
  const marker = postSealMarker(); let clearCount = 0; let refreshed = 0
  const l = loadPage(baseStubs({
    '../utils/formal-stocktake-adapter': { formalStocktakeAdapter: Object.assign(adapter(), { sealPostingCommand: async () => ({}) }), createFormalStocktakeIntentRegistry: () => ({ current: () => null }) },
    '../utils/formal-stocktake-post-recovery': { createFormalStocktakePostRecoveryAdapterFromFormalAdapter: () => ({}), sealFormalStocktakePost: async (lease, sentinel) => { assert.deepEqual(sentinel, marker); lease.clearExact(sentinel); return {} }, submitDurableFormalStocktakePost: async () => ({ detail: detail() }), FormalStocktakePostSubmissionPendingError: class extends Error {} },
    '../utils/formal-stocktake-post-recovery-store': { getFormalStocktakePostRecoveryStore: () => ({ readPending: () => ({ kind: 'valid', values: [marker] }), withTaskLease: async (taskId, work) => work({ read: () => ({ kind: 'valid', value: marker }), clearExact: (value) => { assert.deepEqual(value, marker); clearCount += 1 } }) }) }
  }))
  try {
    const p = instance(l.definition); p._taskId = TASK; p._access = Object.assign({ can_read: true, can_post: true }, identity); p._detail = detail(); p._postRecoveryStore = { readPending: () => ({ kind: 'valid', values: [marker] }), withTaskLease: async (taskId, work) => work({ read: () => ({ kind: 'valid', value: marker }), clearExact: (value) => { assert.deepEqual(value, marker); clearCount += 1 } }) }; p._countRecoveryStore = { readPending: () => ({ kind: 'missing' }) }; p._reviewRecoveryStore = { readPending: () => ({ kind: 'missing' }) }; p._hidden = false; p.data.loading = false; p.load = async () => { refreshed += 1 }; p.refreshPostRecovery(); assert.equal(p.data.postRecoveryCanSeal, true)
    await p.confirmPostSeal(); assert.equal(clearCount, 1); assert.equal(refreshed, 1); assert.equal(p.data.postRecoveryCanSeal, false); assert.equal(p.data.postRecoveryBlocked, false)
  } finally { l.restore() }
})

test('permanent seal failure preserves marker and recovery blocker',async()=>{
  const marker = postSealMarker()
  const l = loadPage(baseStubs({
    '../utils/formal-stocktake-adapter': { formalStocktakeAdapter: Object.assign(adapter(), { sealPostingCommand: async () => ({}) }), createFormalStocktakeIntentRegistry: () => ({ current: () => null }) },
    '../utils/formal-stocktake-post-recovery': { createFormalStocktakePostRecoveryAdapterFromFormalAdapter: () => ({}), sealFormalStocktakePost: async () => { throw new Error('封存接口失败') }, submitDurableFormalStocktakePost: async () => ({ detail: detail() }), FormalStocktakePostSubmissionPendingError: class extends Error {} },
    '../utils/formal-stocktake-post-recovery-store': { getFormalStocktakePostRecoveryStore: () => ({ readPending: () => ({ kind: 'valid', values: [marker] }) }) }
  }))
  try {
    const p = instance(l.definition); p._taskId = TASK; p._access = Object.assign({ can_read: true, can_post: true }, identity); p._detail = detail(); p._postRecoveryStore = { readPending: () => ({ kind: 'valid', values: [marker] }), withTaskLease: async (taskId, work) => work({ read: () => ({ kind: 'valid', value: marker }), clearExact: () => { throw new Error('must preserve marker') } }) }; p._countRecoveryStore = { readPending: () => ({ kind: 'missing' }) }; p._reviewRecoveryStore = { readPending: () => ({ kind: 'missing' }) }; p._hidden = false; p.data.loading = false; p.refreshPostRecovery(); await p.confirmPostSeal(); assert.equal(p.data.postRecoveryBlocked, true); assert.equal(p.data.postRecoveryCanSeal, true); assert.match(p.data.errorMessage, /封存接口失败/)
  } finally { l.restore() }
})
