// One reviewed protocol for Web and WeChat; run --check in the client gate.
import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { stripTypeScriptTypes } from 'node:module';
const source = new URL('../frontend/src/openingStartCore.ts', import.meta.url);
const destination = new URL('../miniprogram/utils/opening-start-core.js', import.meta.url);
if (process.version !== 'v24.19.0') throw new Error('Use the pinned Node 24.19.0 compiler');
const input = await readFile(source, 'utf8');
const names = [];
const code = stripTypeScriptTypes(input, { mode: 'strip' }).replace(/[ \t]+$/gm, '').replace(
  /^export ((?:async )?function|class|const) ([A-Za-z][A-Za-z0-9_]*)/gm,
  (_, declaration, name) => { names.push(name); return `${declaration} ${name}`; });
if (/^\s*(?:import|export)\b/m.test(code) || !names.length) throw new Error('Core must remain self-contained');
const digest = createHash('sha256').update(input).digest('hex');
const output = `// Generated by scripts/sync_opening_start_core.mjs; do not edit.\n// Source SHA256: ${digest}\n` + code +
  `\nmodule.exports = { ${names.join(', ')} };\n`;
if (process.argv.includes('--check')) {
  if (await readFile(destination, 'utf8') !== output) throw new Error('Opening start core is out of date');
  process.stdout.write('Opening start shared core: PASS\n');
} else await writeFile(destination, output);
